### ISSUE TITLE
Incorrectness in surrogate loss

### ISSUE THREAD

**Issue by GolovanovSrg** [reinforceio/tensorforce#106]
https://github.com/reinforceio/tensorforce/blob/172022d6a8e98c34b971dd72f208799c6f583859/tensorforce/models/ppo_model.py#L110

In original paper (https://openai-public.s3-us-west-2.amazonaws.com/blog/2017-07/ppo/ppo-arxiv.pdf), equality 7, take min from clipped ratio and ratio.

**Comment by AlexKuhnle** [comment]
You're right, I just fixed this.
