### ISSUE TITLE
Nan in Beta distribusion

### ISSUE THREAD

**Issue by GolovanovSrg** [reinforceio/tensorforce#114]
https://github.com/reinforceio/tensorforce/blob/d4b6cb2e88947e26e93fbe3d2e580d88759324e0/tensorforce/core/distributions/beta.py#L70

Why don't you use tf.softplus? With custom softplus I have Nan.

**Comment by AlexKuhnle** [comment]
Hi, I just pushed a slight modification which should hopefully fix the issue (essentially clipping extreme values before exp/log). I close the issue, but if the problem persists, please reopen it. The reason why we didn't use the TensorFlow softplus operation is we realized that, for whatever reason, there is no gradient implemented for it (if I remember right).
