### ISSUE TITLE
Optimise Prioritised replay sampling 

### ISSUE THREAD

**Issue by mryellow** [reinforceio/tensorforce#125]
@Kaixhin has this implementation:

https://github.com/Kaixhin/Atari/blob/017959e75fbff75f968b7222857a5aebaf60957c/Experience.lua#L55-L102

https://github.com/Kaixhin/Atari/blob/017959e75fbff75f968b7222857a5aebaf60957c/Experience.lua#L245-L279

There are strata of distributions so that experiences are sampled from throughout the range of priorities, so that some low error experiences are always included. 

I'd jump right in but it's all a bit above my pay-grade. Working understand distributions and sampling, can get how it all fits together if I dig into it deeply enough again but don't have the intuitions for a lot of it to make sense at a glance.

**Comment by michaelschaarschmidt** [comment]
I will have a look, but it might have to wait until after the new optimisers are merged (2-3) weeks, as it's not critical

**Comment by michaelschaarschmidt** [comment]
Fixed via pr #168
