### ISSUE TITLE
Additional tf summaries

### ISSUE THREAD

**Issue by jakeret** [reinforceio/tensorforce#126]
I couldn't figure out how to add more tensorboard summaries.

After I created my agent (`agent = DQNAgent(config=config)`)  I have 

```
self.winning_rate_node = tf.Variable(0.5)
 tf.summary.scalar('winning_rate', self.winning_rate_node)
```

later, during the training I try to update the summary by

```
self.winning_rate_node.assign(winning_rate).eval(session=self.agent.model.session)
```
but then I get `RuntimeError: Graph is finalized and cannot be modified.`

Have I missed something? 
Thanks 
J

**Comment by AlexKuhnle** [comment]
Hi @jakeret,
can you try it again after pulling? I think it should work now -- I removed the graph finalize operation (which probably was kind of pointless anyway, but caused problems every now and then).

**Comment by jakeret** [comment]
Sweet! Works like a charm

Just for completness I had to add:


```
self.winning_rate_node = tf.placeholder(tf.float32, name='winning-rate-placeholder')
self.winning_rate_summary = tf.summary.scalar('winning_rate', self.winning_rate_node)
...

session = self.agent.model.session
winning_rate_summary = session.run(self.winning_rate_summary,
    feed_dict={self.winning_rate_node: winning_rate})
self.agent.model.writer.add_summary(winning_rate_summary,
global_step=self.agent.model.timestep)
```

**Comment by AlexKuhnle** [comment]
Glad it works! 👍
