### ISSUE TITLE
Is GPU being used at all?

### ISSUE THREAD

**Issue by shirishr** [reinforceio/tensorforce#127]
I have Tensorflow 1.3.0 with gpu and openai/gym 0.9.1
I installed tensorforce and ran 
python examples/openai_gym.py CartPole-v0 -a PPOAgent -c examples/configs/ppo_cartpole.json -n examples/configs/ppo_cartpole_network.json
it ran slow and I did not see any load on the gpu
Is there a parameter that I need to set to use gpu?

**Comment by shirishr** [comment]
I installed GPU-Z on my windows 10 machine and confirmed that GPU is being used.
My apologies

**Comment by AlexKuhnle** [comment]
Hehe, I was just about to write an answer. :-)  One problem to keep in mind is that the agent needs to interact with the environment in every timestep, which definitely slows things down. But glad there is nothing fundamentally wrong...
