### ISSUE TITLE
clip_gradients no longer exists?

### ISSUE THREAD

**Issue by trickmeyer** [reinforceio/tensorforce#134]
- clip_gradients - still in the defaults for NAFModel, but not used anywhere.  i recall this being here in the past and it is a common practice - not sure when it was lost.

- tau - this is in a few configs and docstrings, but isn't actually used

**Comment by michaelschaarschmidt** [comment]
We were doing loss clipping not gradient clipping in the q models, so this has been renamed to clip_loss. Gradient clipping might be implemented separately at some point.
fixed tau -> update_target_weight renaming in https://github.com/reinforceio/tensorforce/commit/4884c47e6ff2dac622351bc564782752b31f037e
