### ISSUE TITLE
Replay.get_batch may get wrong next_states when sample the last observation

### ISSUE THREAD

**Issue by bigtreeliujie** [reinforceio/tensorforce#138]
If the last observation's index is sampled, as there is no correct next_states in the memory, the result is wrong.

**Comment by AlexKuhnle** [comment]
You're right. If you could create a pull request with the necessary corrections, that would be great. :-)

**Comment by bigtreeliujie** [comment]
OK，I will create a pull request later.

**Comment by AlexKuhnle** [comment]
Closed, thanks for the PR!
