### ISSUE TITLE
agent.load_model(path=path) NotFoundError

### ISSUE THREAD

**Issue by aGiant** [reinforceio/tensorforce#144]
Hi,
I tried to use agent.save_model() and agent.load_model() without any examples but got errors:

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/llu/Data/Saved_TRPPO/
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
	 [[Node: save/RestoreV2_31/_23 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_122_save/RestoreV2_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

can anyone help me? Thanks

**Comment by michaelschaarschmidt** [comment]
You need to supply the path to the checkpoint file .ckpt, not the directory

**Comment by aGiant** [comment]
Can you give me some example? I have found one example from https://gist.github.com/Tjorriemorrie/40980a4f6c7a96f790a2184cc1714580
but agent.load_model() did not work.

**Comment by michaelschaarschmidt** [comment]
I am using agent.store_model('/username/myfolder/mymodel.ckpt'), and agent.load_model('/username/myfolder/mymodel.ckpt') with full paths.

That  aside, this is a tensorflow mechanics issue, not a tensorforce bug, I would suggest consulting the tensorflow documentation to understand checkpointing; I will close this in the meantime.

**Comment by aGiant** [comment]
I do not think that is tensorflow issue! I have tried what you suggested with a name ".ckpt". But there are four different files (NOT ONE with XXX.ckpt but FOUR) produced by tensorforce which is NOT the same way what tensorflow does.

**Comment by AlexKuhnle** [comment]
It's definitely the case that TensorFlow (depending on the arguments to `tf.train.Saver`) creates more than one file. Can you post the lines where you save/load the model? One thing that I found on StackOverflow is the issue [here](https://stackoverflow.com/questions/42260167/unsuccessful-tensorslicereader-constructor-failed-to-find-any-matching-files-fo). If you save it in the current directory, that could be the problem.

**Comment by aGiant** [comment]
I had those:
path = "/home/llu/Data/Saved_NAF/naf_model.ckpt"
agent.save_model(path=path)
agent.load_model(path=path)

then errors.

**Comment by AlexKuhnle** [comment]
What if you remove the suffix ".ckpt"? Otherwise we might have to investigate whether we're doing the restoring wrong, since we're not quite following what e.g. they do [here](https://stackoverflow.com/questions/33759623/tensorflow-how-to-save-restore-a-model), using [this method](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/train/import_meta_graph).

**Comment by aGiant** [comment]
Without .ckpt:
INFO:tensorflow:Restoring parameters from /home/llu/Data/Saved_NAF/naf_model
[2017-09-29 21:34:31,259] Restoring parameters from /home/llu/Data/Saved_NAF/naf_model
2017-09-29 21:34:31.300080: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/llu/Data/Saved_NAF/naf_model

INFO:tensorflow:Restoring parameters from /home/llu/Data/Saved_NAF/naf_model
[2017-09-29 21:34:31,259] Restoring parameters from /home/llu/Data/Saved_NAF/naf_model
2017-09-29 21:34:31.300080: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/llu/Data/Saved_NAF/naf_model

**Comment by AlexKuhnle** [comment]
Yeah, okay, then we have to look into this. What you could do, if you want, is to change the load_model function to what they do in the links I posted and see whether it works.

**Comment by michaelschaarschmidt** [comment]
Please post the content of the folder, all files. If there is a file of the form .ckpt-XXXX with some number, that is the step you last trained and you have to provide that as the load path

**Comment by aGiant** [comment]
Thanks, guys. Now it works.
