### ISSUE TITLE
agent.save_model issue!!

### ISSUE THREAD

**Issue by aGiant** [reinforceio/tensorforce#145]
Hi,
Again, this is a bug of tensorforce. In docs, agent.save_model has two parameters: path and use_global_step. But in the new version, I have written:
agent.save_model(path=path, use_global_step=False)
Then got:
TypeError: save_model() got an unexpected keyword argument 'use_global_step'

That is not a bug of tensorflow. If I wrote save to "mymodel.ckpt" then I got "mymodel.ckpt". Did anyone really try to call save_model() and load_model() functions??

**Comment by michaelschaarschmidt** [comment]
Please post this in the other issue. In any case, the point is that you are calling a parameter that is only available on the model's method on the *agent*. We can make this available on the agent too, it was just for internal use thus far.

I will summarise:

The default behaviour is that global step is true. Checkpoint contains the step. In that case, you can only reload by using the correct global step in the file. The checkpoint file will be .ckpt-XXXXX where X is global step.

OR you set global step to false, then the checkpoint file will just be .ckpt, which was currently only available on the *model* not the agent, so you can trivially use it by calling agent.model.save_model(path=path, use_global_step=False), and we can adjust the API there.
