### ISSUE TITLE
Easier Tensorboard Customization

### ISSUE THREAD

**Issue by trickmeyer** [reinforceio/tensorforce#146]
Ideally the user should be able to define what they want to log in Tensorboard.  The current challenge is that the fetches and feed_dict required to get many of the possible values of interest may not be easy to expose.

One approach would be to create a few hooks or callbacks where the user could run the updates themselves with supplied variables.  Generalizing that across models may not be easy, however.

Sorry this isn't more specific, but I know this item is of interest to at least @Islandman93 and me, so I wanted to get it out there for thoughts.

**Comment by AlexKuhnle** [comment]
Hi @trickmeyer (and @Islandman93),
what do you think about the summary handling in dev (and I think this mechanism came up at some point in Gitter): There is a set of "summary tags" like 'total-loss', 'variables', etc which are defined in the config (e.g. [here](https://github.com/reinforceio/tensorforce/blob/dev/tensorforce/agents/vpg_agent.py#L66)), and the implementation can then check whether a certain tag is requested (e.g. [here](https://github.com/reinforceio/tensorforce/blob/dev/tensorforce/models/model.py#L452)). Makes it possible to select only what is of relevance and allows new models to introduce completely new tags (as long as they don't clash with old ones). We haven't (yet) integrated the `SummarySessionWrapper`, but cleaned up the summary handling in `Model` in general. Essentially, we use the TensorFlow `Supervisor` class which we realized seems to internally handle summary writing every X seconds, so if there are no problems arising with using `Supervisor`, I think that might be the best way to handle it.
I close the issue for now, but feel free to re-open if you feel that doesn't quite reflect what you had in mind.

**Comment by trickmeyer** [comment]
I think it's a good idea to see how the new version feels after some use.

I prefer a lot of Tensorboard logging for debugging and introspection, so I personally use a branch where I pass in a tf.writer I create on my own, so I'll se how that plays along with your `Supervisor` plan.

**Comment by AlexKuhnle** [comment]
Yes, definitely. So currently by default the `Supervisor` writes the log into `config.model_directory`, but it also allows to pass your own writer, if that is desirable (could be done via an optional config value). Would there be an advantage vs `Supervisor` internally creating one?

**Comment by AlexKuhnle** [comment]
We don't so far use it very much, so insight into how others are using Tensorboard logging and what the points to consider are is very welcome.

**Comment by trickmeyer** [comment]
I pass one in / expose it for two main reasons:

1. I actually create two writers to two different subdirectories: one for train, one for test.  Doing so allows me to get series of internals/performance/etc. for train and test on the same Tensorboard "graphs".

2. I write protocol buffers directly to those writers on the episode complete callback for some custom stuff that doesn't work quite as well out of the box.  That writing is "outside" of Tensorforce.  Although I could go ahead and grab the attribute off the model, it just makes more sense for my main script to create it and use it there.

**Comment by AlexKuhnle** [comment]
Okay, so it does make sense to allow passing your own writer. This could be, for instance, done via an optional config argument since, as mentioned, the `Supervisor` allows to set your own writer. Any problems you can see apart from that with leaving the summary fetching to the TensorFlow class?

**Comment by trickmeyer** [comment]
I actually swap out the writer (train/test) every `n` episodes when I run my separate validation runner (the main episode end callback loop triggers it), and I do so by simply setting the writer attribute.  So long as I can continue to do that I think it's fine.

**Comment by AlexKuhnle** [comment]
As you maybe have seen in Gitter as well, the summaries are now recorded using the TF `SummarySaverHook` class, by specifying the following config entry: `summary_spec=dict(directory={str}, seconds={int}, labels=['total-loss', 'variables', etc])`. If you want to swap the writer, you have to change the attribute in this hook, for which I added the `Model.summary_writer_hook` attribute, so by reassigning `Model.summary_writer_hook._summary_writer`, it should hopefully work. I haven't actually tried it myself, so please re-open if it doesn't.
