### ISSUE TITLE
Continuing training

### ISSUE THREAD

**Issue by tms1337** [reinforceio/tensorforce#156]
Just a quick question, if I load the preexisting model and run the runner on it does it continue with the training? I assume it does but I need to be sure since we are going to use this system in production environment.

Also if I have this expoloration configuration

```
exploration=dict(type='epsilondecay',
                             epsilon=1,
                             epsilon_final=0.05,
                             epsilon_timesteps=100*10**3,
                             start_after=0),
```

is it restarted in the new run or the state of the exploration config is taken from the loaded model?

**Comment by michaelschaarschmidt** [comment]
We have recognised this recently and have experimentally fixed it in our own benchmarking script, see:
https://github.com/reinforceio/tensorforce-benchmark/commit/bf0163ad54b050e092ba72d2be1e6941667f1c98
