### ISSUE TITLE
Test/Validation Runner

### ISSUE THREAD

**Issue by trickmeyer** [reinforceio/tensorforce#158]
Create a runner with deterministic=True to run a trained model on a test/validation set.

**Comment by AlexKuhnle** [comment]
FYI: Will be part of the update soon-to-come.

**Comment by mryellow** [comment]
Note: OpenAIGym package `register` function includes a flag for `nondeterministic`.

https://github.com/openai/gym/blob/master/gym/envs/__init__.py
https://github.com/openai/gym/blob/master/gym/envs/registration.py

**Comment by AlexKuhnle** [comment]
As mentioned before, the runner flag exists now ([here](https://github.com/reinforceio/tensorforce/blob/dev/tensorforce/execution/runner.py#L56)), so I assume I can close this issue.

@mryellow, this would be a separate feature, non-deterministic environment (as opposed to non-deterministic action choice), right? Could be integrated into the `OpenAIGym` environment as optional argument. Feel free to PR... ;-)
