### ISSUE TITLE
Gaussian log_stddev clipping - min > max; leads to constant log_stddev

### ISSUE THREAD

**Issue by trickmeyer** [reinforceio/tensorforce#161]
[This line](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/distributions/gaussian.py#L65) leads to a constant log_stddev.

```
import tensorflow as tf
a = tf.placeholder(tf.float32)
b = tf.clip_by_value(a, 0.01, -0.01)
with tf.Session() as sess:
    b_out = sess.run(b, feed_dict={'a': 0})
with tf.Session() as sess:
    b_out = sess.run(b, feed_dict={'a': 0.02})
with tf.Session() as sess:
    b_out = sess.run(b, feed_dict={'a': -0.02})

```
all return b_out as 0.01.  Looking into the [implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/clip_ops.py#L33), it's clear that clip is implemented as:

`clip(a, clip_min, clip_max) = max(clip_min, min(a, clip_max))`

which will always return `clip_max` when `clip_max < clip_min`

**Comment by mryellow** [comment]
> which will always return clip_max when clip_max < clip_min

Unless input is negative.

```
python -c "import tensorflow as tf; print(tf.Session().run(tf.clip_by_value(-2.0, 0.01, -0.01)))"
0.01
```

**Comment by trickmeyer** [comment]
Not an issue, since we're clipping based on a negative value.  My bad.
