### ISSUE TITLE
vpg_agent_visual baseline size error

### ISSUE THREAD

**Issue by ImpulseAdventure** [reinforceio/tensorforce#165]
Minor issue: I believe the `vpg_agent_visual.json` example config may have a typo in its baseline definition. Currently the sub-dict defines the key `"size"` whereas the `MLPBaseline` expects `"sizes"`.

Existing code:
`
  "baseline": {
    "type": "mlp",
    "size": 100,
    "epochs": 5,
    "update_batch_size" : 128
},
`
Suggested replacement:
`
  "baseline": {
    "type": "mlp",
    "sizes": [100],
    "epochs": 5,
    "update_batch_size" : 128
},
`

**Comment by michaelschaarschmidt** [comment]
Thank you for pointing it out, will fix

**Comment by michaelschaarschmidt** [comment]
Fixed in release
