### ISSUE TITLE
Possible memory leak in DQNAgent

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#175]
We batted this around in Gittr, but I'm getting pretty confident there's indeed a mem leak in DQNAgent (or a parent). At least something worth keeping an eye out for while y'all are working on the rewrite. 

Here's my scoop. I'm working with a whole episode's worth of data at once (a window of cryptocurrency timesteps), so every reset there's a solid amount of data (maybe 50-100 megabytes). I can run PPO, NAF, VPG, TRPO forever (I've ran PPO to 48h), no memory issues. When I run DQNAgent specifically, my memory balloons quickly, and after about 30m maxes my system (16GB) and crashes the script. I'd've pegged it as user-error (maybe `env.close()`) except that all other agents run no problem, with no caller-code difference. I mean hey, DQN is a MemoryAgent - it's manually keeping/discarding memory, so it's not unlikely?

This is with both #master and #dev. I've tried finalizing the graph in #master (not yet in #dev, need to look into). It's not a pressing issue for me, so no rush. I'm currently focused on PPO, and I'm sure most of your users aren't dealing with tons of data at once. Just flagging to keep an eye out for. I'll see if I can come up with a simple replicable case in quickstart or such.

**Comment by AlexKuhnle** [comment]
If you find a replicable case, that would be great. How big is your memory (memory_capacity)? The default is one million instances, so that could easily become quite a lot, depending on your state space. The memory didn't change in the dev branch, but will likely be focus of the next 'version'.

**Comment by lefnire** [comment]
I'm a total idiot, that was exactly it. 1M instances of heavy data, it maxes before it reaches capacity! Set it to 50k & problem solved. Sorry for all the wolf-crying Alex, thanks for your patience!
