### ISSUE TITLE
Feature Request: NoisyNet for exploration

### ISSUE THREAD

**Issue by ImpulseAdventure** [reinforceio/tensorforce#182]
The introduction of *NoisyNets* appears to add significant explorative capability to DQN & A3C, in some cases making progress on tasks that had otherwise exhibited little advancement.

I wasn't sure which enhancements might be considered for the roadmap once 0.3.0 has stabilized, but thought I would suggest this as a low-priority wishlist item in case there may be interest in developing further variants.

Reference: https://arxiv.org/pdf/1706.10295.pdf

**Comment by michaelschaarschmidt** [comment]
This is a sensible request - FWIW aside from the plan for 0.4.0 (improved device assignments and distributed execution semantics), we will make a more detailed list of potential contributions to guide the community

**Comment by AlexKuhnle** [comment]
Hi @ImpulseAdventure,

I just added a parameter adding basic variable noise when retrieving an action via a new parameter `variable_noise` (giving the stddev of the noise to add if not None). [Here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L550) the relevant part of the `Model` code. Still have to look at the paper in more detail, what additional tricks they use and whether/how we can integrate them, but this option should be a start...

**Comment by etardis** [comment]
Alex,

That looks like a good start and approach.  The paper has 2 methods and for some reason sets Mu during Initialization.  I am sure that can all get straightened out.

It isn't clear what needs to be done during inference, so it might be good to set the NoiseLevel into the graph as a variable and have a method to assign() that variable during training or for inference.  This will allow Noise to be set to 0.0 if needed or decreased with temperature if needed.  It just might offer some flexibility while providing the basic implementation as documented in the paper.

**Comment by AlexKuhnle** [comment]
Yes, could be done, would mean that the variable noise becomes its own small module. This will probably something for later on. For now, one could use the `deterministic` flag to turn noise off, however, currently this flag is kind of dependent on the model, so need to think about that.

**Comment by ViktorM** [comment]
Hi! Is there any progress with noisy nets implementation? Or at least some timeline?

**Comment by AlexKuhnle** [comment]
Hi @ViktorM, there is a timeline, but noisy nets are not high on the priority list. The `variable_noise` parameter explained above is a first step, but doesn't incorporate all the implementation details of the papers. If you want to look into it, what is missing, etc, and you have questions, let us know. Regarding the `deterministic` flag mentioned in my last post, I can potentially look into that.

**Comment by AlexKuhnle** [comment]
Variable noise is only applied for `act()`, other details are up to contribution.
