### ISSUE TITLE
Implement KFAC-optimizer

### ISSUE THREAD

**Issue by michaelschaarschmidt** [reinforceio/tensorforce#183]
Necessary for ACKTR but would also be available for other models via the new optimizers.

**Comment by daggertye** [comment]
There is a KFAC optimizer in tensorflow now, but it's still in contrib. 

https://www.tensorflow.org/api_docs/python/tf/contrib/kfac/optimizer/KfacOptimizer

**Comment by AlexKuhnle** [comment]
Note that this optimizer relies on using `tf.layers`, though, so unfortunately not (fully) compatible with TensorForce.
