### ISSUE TITLE
Enforce alpha/beta > 1 in Beta distribution (ensure unimodal + concave)

### ISSUE THREAD

**Issue by michaelschaarschmidt** [reinforceio/tensorforce#184]
Beta distribution currently allows 0 < alpha/beta instead of 1 < alpha/beta as suggested in paper:

http://proceedings.mlr.press/v70/chou17a/chou17a.pdf

**Comment by AlexKuhnle** [comment]
What do you mean by changing alpha/beta? When initializing the distribution, [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/distributions/beta.py#L30)?
