### ISSUE TITLE
A3C status/example?

### ISSUE THREAD

**Issue by wangell** [reinforceio/tensorforce#187]
Is A3C actually implemented as of now? I can't seem to find a way to actually use it (and global optimizer seems to be commented out in https://github.com/reinforceio/tensorforce/blob/9ff94e69a2d19eeb6975fde613b31173f4601f25/tensorforce/core/optimizers/__init__.py

I have several copies of the environment that I want to train against, but not necessarily in a multi-threaded way.  Is there a way I can do this currently?  The main issue right now is decoupling the implied sequencing in the agent/model structure - I want to be able to call agent.act(state) and then agent.observe(reward), and use A3C to combine model updates to the global model.  Do I have to construct multiple models under the same agent?  Is this something I need to implement myself?  Ideally I would just pass in a list of environments to an agent which would handle all the semantics.

**Comment by AlexKuhnle** [comment]
Hi @wangell,

The [examples/openai_gym_async.py](https://github.com/reinforceio/tensorforce/blob/master/examples/openai_gym_async.py) should work, which you can use as guidance if you want to setup your own customized runner script. The reason why `GlobalOptimizer` is commented out is that it shouldn't be available as optimizer key to *'just set'* (at least not yet), but it is used when setting corresponding config arguments. Distributed/concurrent/async execution is on the roadmap for the next big update, which is however still many weeks away -- we haven't started yet. The above script allows you to run multiple independent models on separate environments, which update a global model and sync their own parameters with it. That's the only mode currently supported, unfortunately.

**Comment by AlexKuhnle** [comment]
So: Yes, A3C works, if you start the above script using the `VPGAgent` (`-a vpg_agent`) with a baseline.

**Comment by nskplta** [comment]
Hi @AlexKuhnle, would you be so kind of explaining a bit more how to implement A3C as you say: 

> if you start the above script using the VPGAgent (-a vpg_agent) with a baseline 

This would be of great help, many thanks!!

**Comment by AlexKuhnle** [comment]
Sorry for the very late answer, but if you haven't made any progress yet, I hope [this](https://github.com/reinforceio/tensorforce/blob/master/examples/openai_gym_async.py#L23) helps.
