### ISSUE TITLE
Preprocessor Nomenclature Standardize & Normalize

### ISSUE THREAD

**Issue by Mazecreator** [reinforceio/tensorforce#189]
I think the naming of some of the Preprocessor functions could be changed to better represent what is occurring.  In particular, there are two that I found "Center" and "Normalize".

"Center" seems to describe a Normalization function scaling the input to the range [0,1].

"Normalize" seems to describe a Standardization function of creating a Z score or a distribution of mean =0 and STD =1.0.

I would recommend renaming "Center" to "Normalize" and "Normalize" to "Standardize".  Here is a good reference:
http://www.dataminingblog.com/standardization-vs-normalization/

**Comment by michaelschaarschmidt** [comment]
Done in https://github.com/reinforceio/tensorforce/commit/a0d6d8b0427f81ce789b8fbc8a0de76f4934e144
