### ISSUE TITLE
Prioritized Replay Memory Bugs

### ISSUE THREAD

**Issue by ashokpant** [reinforceio/tensorforce#190]
PrioritizedReplay([tensorforce/core/memries/prioritized_replay.py](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/memories/prioritized_replay.py)) is not properly upgraded.
Common errors are:

- Parameters in init method (states_config--> states_spec, actions_config-->actions_spec)
- Accessing dict elements in get_batch method(state.shape-->state['shape'], state.type-->state['type'], etc.). Also teminals--> terminal and rewards-->reward in return dict. 
- update_batch method "For all instances a loss value has to be provided." error. Here, output loss_per_instance dimension is one less than the batch size. This is may be due to the error in tf_loss_per_instance method of [tensorforce/models/q_model.py](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/q_model.py). Using same internals fix the problem, but is this correct?

**Comment by michaelschaarschmidt** [comment]
Yes sorry, this is because we merged the new faster implementation - will fix by the weekend.

**Comment by AlexKuhnle** [comment]
Fixed the mentioned issues. However, there are some more fundamental issues for which I will open a separate issue.
