### ISSUE TITLE
Double DNQ double_q_model =True removed

### ISSUE THREAD

**Issue by etardis** [reinforceio/tensorforce#194]
I think there was a mistake in the last Pull Request on ddqn_agent.py:
https://github.com/reinforceio/tensorforce/blob/master/tensorforce/agents/ddqn_agent.py#L127

In the default parameters the parameter that enables the double_q feature in the model class was removed so it might not enable Double DNQ but act like the standard DNQ agent.

I think this needs to be added back into that file:
double_q_model =True

**Comment by etardis** [comment]
Okay, found the parameter moved to "obligatory".  Not sure the difference by adding it to that section.

**Comment by AlexKuhnle** [comment]
Hi @etardis,

sorry for this, we still want to improve the config situation in the next weeks, to make it more obvious what happens. The reason this was changed is that DDQN should internally *always* set ` double_q` to ` True`, while what is specified in the `default_config` is what could be modified generally (which for DDQN in this case would be weird).
