### ISSUE TITLE
Tensorforce fresh installation

### ISSUE THREAD

**Issue by Davidnet** [reinforceio/tensorforce#195]
Hello!, Nice work by the way.

On a fresh installation of tensorforce I'm getting this error of:
`Expecting property name enclosed in double quotes `

while running:

`python examples/openai_gym.py CartPole-v0 -a ppo_agent -c examples/configs/ppo_agent.json -n examples/configs/ppo_network.json`

**Comment by Davidnet** [comment]
pip version has a trail over comma on ppo_network json.

**Comment by Davidnet** [comment]
I submitted a PR

**Comment by krfricke** [comment]
we updated the pypi version just now to 0.3.0 in 6a556f4. thanks for the reminder
