### ISSUE TITLE
Upgrade examples/threaded_ale.py to 0.3.0

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#197]
Big fan of parallel-ran models (have had better performance w/ such). I used a `threaded_ale.py` before the upgrade, but it looks like it's incompatible with the new setup. Previously you could pass `model=` as a constructor arg to an agent, and it would use that model instead of instantiating it's own; that argument no longer exists, so threaded_ale won't run. Might be something obvious, but I couldn't figure out how to accomplish similar in 0.3.0.

**Comment by AlexKuhnle** [comment]
Hey, true, this is a file we haven't looked into yet, should do that over the weekend.

**Comment by michaelschaarschmidt** [comment]
Updated
