### ISSUE TITLE
Documentation clarification on "States"

### ISSUE THREAD

**Issue by Mazecreator** [reinforceio/tensorforce#201]
I am looking to pass a Multimodal  state for a custom environment.  For example like the following:

    states = dict(
        env=dict(shape=(64,), type='float'),
        mp=dict(shape=(3,), type='int')
    )

My confusion is around this statement in the blog: "Note that the single-state/action short-form has to be used consistently for communication with the agent throughout the code."

I am not sure what that means for my execute(self,actions) method for state.  How do I return this state from that function?  Do I use a dictionary to return the float and int parts?

**Comment by michaelschaarschmidt** [comment]
Your dictionary needs to be of the form
dict(
env=[1.0,..,64.0] , # float array
mp=[1, 2,3] # int array
)

The short form applies if you have a single state, then you can pass the state as an array, instead of a dict with dict(state=state)

**Comment by AlexKuhnle** [comment]
Just want to add: The 'consistency' is about the special single-state case with shortform `dict(type=..., shape=...)`, which is internally converted to `dict(state=dict(type=..., shape=...))`. If you use the shortform without `state=`, then you have to always use the shortform, or vice versa, so when you specify the action space and whenever you pass actions to the agent, you need to be consistent.
