### ISSUE TITLE
Returning False from episode_finnished should stop training. Exception is raised but control is not returned to program

### ISSUE THREAD

**Issue by slundell** [reinforceio/tensorforce#205]
I use logic in episode_finnished to test if there has been any improvement on performance. If it has not for the last X episodes, the training should stop. I do this by returning False in episode_finnished. A TF exception is raised, but control is not returned to your program (to execute whatever is after runner.run()) 

I suspect this is because supervisor.should_stop() might not be checked in Runner.

**Comment by AlexKuhnle** [comment]
Can you give a small example, like a Gym environment, where we can reproduce the behavior? That would be helpful...

**Comment by slundell** [comment]
Turns out this only happens if config['model_dirctory'] is set. The code below fails with an exception about two meters tall :) Comment out model_directory in config and it executes as expected.


`tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'ppo/state' with dtype float and shape [?,4]`

`from tensorforce import Configuration
from tensorforce.agents import PPOAgent
from tensorforce.execution import Runner
from tensorforce.contrib.openai_gym import OpenAIGym

env = OpenAIGym('CartPole-v0')

config = Configuration(
        tf_session_config=None,
        model_directory="./models/",
        batch_size=4096,
        )

network_spec = [
    dict(type='dense', size=32, activation='tanh'),
    dict(type='dense', size=32, activation='tanh')
]

agent = PPOAgent(
    states_spec=env.states,
    actions_spec=env.actions,
    network_spec=network_spec,
    config=config
)


def episode_finished(r):
    print("finished episode: {}".format(r.episode))
    return r.episode < 50


runner = Runner(agent=agent, environment=env)
runner.run(episodes=3000, max_episode_timesteps=200, episode_finished=episode_finished)
print("Done training. Will not get here if config['model_directory'] is set.")

`

**Comment by AlexKuhnle** [comment]
Hey @slundell,

We realized a problem related to `model_directory` and `Supervisor` etc, and working on a solution. I think this here might be affected by the problem as well, so hope it's gonna soon be solved.

**Comment by AlexKuhnle** [comment]
Hey @slundell,

several things related to the `Supervisor` class are now modified and updated, one of them being that `should_stop`, now of `MonitoredSession`, is checked in the `Runner`. Also `model_directory` and related functionality is updated to `saver_spec` (best see Gitter). Hope it solves the problem, but please re-open if it still comes up.
