### ISSUE TITLE
Summary/Model Path settings fails at HEAD

### ISSUE THREAD

**Issue by Mazecreator** [reinforceio/tensorforce#207]
I am trying to create summaries with the current HEAD https://github.com/reinforceio/tensorforce/commit/046954c1bf43d3464e3d719ce8b074f9a9453882 it is possible my version is not exact as I have a pending PULL which I keep hacking in, but that should only affect Network building.

        model_directory=DataDir,
        summary_logdir=DataDir,  
        save_frequency=60,  # TensorFlow default
        summary_labels=['total-loss'], #,'losses','variables','activations','relu'],
        summary_frequency=120,  # TensorFlow default

I have tried a few different agents but with the DQNAgent() I get the following if I set those paths:
```
Configuration values not accessed: summary_logdir
2017-11-01 16:24:05.281237: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,7] has negative dimensions
2017-11-01 16:24:05.281328: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,7] has negative dimensions
	 [[Node: dqn/state = Placeholder[dtype=DT_FLOAT, shape=[?,7], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
2017-11-01 16:24:05.282895: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,7] has negative dimensions
2017-11-01 16:24:05.282952: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,7] has negative dimensions
	 [[Node: dqn/state = Placeholder[dtype=DT_FLOAT, shape=[?,7], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
2017-11-01 16:24:05.283659: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,7] has negative dimensions
2017-11-01 16:24:05.283690: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,7] has negative dimensions
	 [[Node: dqn/state = Placeholder[dtype=DT_FLOAT, shape=[?,7], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

I have 7 features and set the path in the Configuration.  When I remove both of these settings from configuration it runs fine, but no logs to view with TensorBoard.

**Comment by AlexKuhnle** [comment]
Hey @Mazecreator,

I just pushed some changes that I was working on, which update the session/saver/summary/etc handling, since the TF class `Supervisor` is (or will be) deprecated, apparently. New config API and some possible entries:

```python
saver_spec=None or dict(directory={str}, seconds={int} [, load={bool, default True}])
summary_spec=None or dict(directory={str}, steps={int})
```

For more details currently best to have a look at the code. Also, I'm not sure whether the TF `SummarySaverHook` works as expected in this setup right now, we have to check that.

Hope that works well for you, please re-open if not.

**Comment by Mazecreator** [comment]
Looks good, just dropping a few more hints for future help, need labels to add data to summary:

    summary_spec=dict(directory=CkptDir, steps=5,labels=['losses','variables'])

This occurs in the Network as well:

    network_spec = [
        dict(type='dense', size=5, activation='relu', skip=False,summary_labels=['relu','activations','variables']),
        dict(type='dense', size=None, activation='relu', skip=False,summary_labels=['relu','activations','variables']),
        dict(type='dense', activation='relu', skip=False,summary_labels=['relu','activations','variables']),
        dict(type='dense', activation='relu', skip=False,summary_labels=['relu','activations','variables'])
    ]        

Hopefully I didn't miss any of the labels.

**Comment by AlexKuhnle** [comment]
Yes, sorry, I forgot to add the `labels` entry. However, I'm surprised about the `summary_labels` in the `network_spec` -- are they really necessary? If so, I will look into it, because that shouldn't be the case...

**Comment by Mazecreator** [comment]
I only did a quick run through the code for Summary Label references.  I found them in the layer.py file, it appeared the summary_labels came through the "network_spec" but I could be wrong.  I am not fully up on the API and library structure yet.

https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/layer.py#L38-L55

**Comment by AlexKuhnle** [comment]
If you could try it without these entries in the network_spec and verify that it still works, that would be great. On instantiation of the network, these labels should be passed ([here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/distribution_model.py#L60)).

**Comment by Mazecreator** [comment]
I tried it both ways and got somewhat different results in TensorBoard.  I thought maybe duplicates, but didn't see any.  A new section "loss-per-instance" actual shows when adding "summary_labels" as below:

```
    network_spec = [
        dict(type='dense', size=5, activation='relu', skip=False,summary_labels=['relu','activations','variables']),
        dict(type='dense', size=None, activation='relu', skip=False,summary_labels=['relu','activations','variables']),
        dict(type='dense', activation='relu', skip=False,summary_labels=['relu','activations','variables']),
        dict(type='dense', activation='relu', skip=False,summary_labels=['relu','activations','variables']),
    ]  
...
summary_spec=dict(directory=CkptDir, steps=5,labels=['losses','variables']),     
```
<img width="1926" alt="screenshot 2017-11-08 10 27 23" src="https://user-images.githubusercontent.com/18412448/32557564-89862412-c470-11e7-9a9b-188e48be80a0.png">

when I remove the summary_labels from the network_spec and use just the summary_spec:

    summary_spec=dict(directory=CkptDir, steps=5,labels=['relu','activations','losses','variables']),    

I get less information:

<img width="1926" alt="screenshot 2017-11-08 10 26 36" src="https://user-images.githubusercontent.com/18412448/32557714-ed6bd152-c470-11e7-9b19-1880944ebf9d.png">

I am new to your API and not sure what all these variables are yet so there may be duplicates just renamed I don't detect.  On a side note, it looks like the per-layer summary_labels might allow for finer control (as a feature) for debugging certain layers and ignoring other...

**Comment by AlexKuhnle** [comment]
I agree that it can be useful for fine control, and no plans to disable to specify labels like that, it's only that specifying them 'globally' should also work. I think I know what's going on there: The target network in DQN is only called during the update / `loss_per_instance`, hence these variables are registered there, while the others are first created in `actions_and_internals`. Passing the `labels` argument to the target network was missing.

**Comment by Mazecreator** [comment]
Okay,

Let me know when you commit a change for this and I will test it again.

**Comment by AlexKuhnle** [comment]
I committed the change now. Thanks for trying again! :+1:

**Comment by Mazecreator** [comment]
Looks like you got it, now the same results either way.
