### ISSUE TITLE
EWC integration?

### ISSUE THREAD

**Issue by ashokpant** [reinforceio/tensorforce#209]
Does tensorforce have any plan to integrate [Elastic Weight Consolidation](https://arxiv.org/abs/1612.00796)  to overcome the catastrophic forgettings in the neural networks? 
I don't find any notes if it is already implemented or is it actually needed or not.

**Comment by AlexKuhnle** [comment]
It's not on the roadmap for the near future, but if you want to look into it, a PR is always welcome (and we try to be of help on the way).
