### ISSUE TITLE
Create FAQ for new users

### ISSUE THREAD

**Issue by michaelschaarschmidt** [reinforceio/tensorforce#210]

**Comment by slundell** [comment]
This would be very helpful. I would also suggest some guide/table that helps you select algo and hyper parameters suitable for your environment.

**Comment by michaelschaarschmidt** [comment]
So selecting algorithms and hyper parameters is actually beyond what we can provide open source and would be part of commercial support - the faq will more tell people where to find what, and how certain mechanisms can be used - not how they should use them for their problem.

**Comment by michaelschaarschmidt** [comment]
Created a first version of a FAQ which will be now expanded over time to add common questions:
https://github.com/reinforceio/tensorforce/blob/master/FAQ.md
