### ISSUE TITLE
Are all "tensorforce/tests" unittest modules supposed to pass?

### ISSUE THREAD

**Issue by wenkesj** [reinforceio/tensorforce#211]
I am using the latest clone from my [fork](https://github.com/wenkesj/tensorforce)

Are all tests supposed to pass? I just ran a random test to check to see if I can verify my changes and got some failing.

Maybe this is because of the changes I made elsewhere? (which aren't under the tests or \*DQN\* modules)

```sh
$ python -m unittest tensorforce.tests.test_dqn_agent.TestDQNAgent

DQNAgent (bool):?/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))

 171 169 170 214 163 ==> 5 passed
...
DQNAgent (int): 108 113 3000 3000 102 ==> 3 passed
F
DQNAgent (lstm): 555 180 100 103 100 ==> 5 passed
.
DQNAgent (multi): 3000 416 3000 3000 3000 ==> 1 passed
F
======================================================================
FAIL: test_int (tensorforce.tests.test_dqn_agent.TestDQNAgent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "?/tensorforce/tensorforce/tests/base_agent_test.py", line 78, in test_int
    config=self.__class__.config
  File "?/tensorforce/tensorforce/tests/base_test.py", line 87, in base_test
    self.assertTrue(passed >= 4)
AssertionError: False is not true

======================================================================
FAIL: test_multi (tensorforce.tests.test_dqn_agent.TestDQNAgent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "?/tensorforce/tensorforce/tests/base_agent_test.py", line 189, in test_multi
    config=self.__class__.config
  File "?/tensorforce/tensorforce/tests/base_test.py", line 87, in base_test
    self.assertTrue(passed >= 4)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 298.487s

FAILED (failures=2)
```

Thank you, I am looking forward to making some contributions to this amazing repo!

**Comment by michaelschaarschmidt** [comment]
Hi,

we recently rolled out a major update (0.3) with the new optimizer API. Tests are supposed to all pass but are still debugging the new release. Test-multi might have to be reconfigured

**Comment by wenkesj** [comment]
@michaelschaarschmidt thanks for the reply, I am using the update 0.3 as I pulled yesterday from the master. Is there any documentation on how tests are run specifically for this library so I could see how the results are supposed to look?

**Comment by michaelschaarschmidt** [comment]
Oh you are running them correctly according to your output. What I am saying is that right now, not all tests are passing because the release still has a few issues

**Comment by wenkesj** [comment]
@michaelschaarschmidt ahhh! okay, cool. I'll keep my changes local until things get fixed upstream.
