### ISSUE TITLE
Example openai_universe.py  "cannot import name create_agent"

### ISSUE THREAD

**Issue by Mazecreator** [reinforceio/tensorforce#213]
I tried to run one of the examples to test CONV2D, but encountered an error:

    python examples/openai_universe.py -a DQNAgent -c examples/configs/dqn_agent.json -n examples/configs/dqn_network.json flashgames.DuskDrive-v0

I got this error:
```
Traceback (most recent call last):
  File "examples/openai_universe.py", line 42, in <module>
    from tensorforce.agents import create_agent
ImportError: cannot import name create_agent
```

**Comment by michaelschaarschmidt** [comment]
API is not updated for that example. Actually I am wondering if this example should be deleted if universe is not actively developed any more and most people seem to be using gym

**Comment by Mazecreator** [comment]
Okay, I will see if I can find another CONV1D and CONV2D network that is supported by another example.  Just need it to test the skipping, I don't have a dataset that will provide the Rank 3 and Rank 4 input data requirement.

**Comment by Mazecreator** [comment]
Tried to use "openai_gym.py" but I am getting a different error, I think because of the agent, seems to want something in a module.name format:

with this command:

    python3 examples/openai_gym.py -a DQNAgent -c examples/configs/dqn_agent.json -n examples/configs/dqn_network_visual.json CartPole-v0

```
Traceback (most recent call last):
  File "examples/openai_gym.py", line 135, in <module>
    main()
  File "examples/openai_gym.py", line 84, in main
    config=config
  File "/home/greg/library/tensorforce/tensorforce/agents/agent.py", line 345, in from_spec
    kwargs=kwargs
  File "/home/greg/library/tensorforce/tensorforce/util.py", line 155, in get_object
    module_name, function_name = obj.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by michaelschaarschmidt** [comment]
Yes, please check the updated Readme example, you need to provide dqn_agent, not DQNAgent
