### ISSUE TITLE
Epsilon Annealing bug

### ISSUE THREAD

**Issue by Islandman93** [reinforceio/tensorforce#228]
Epsilon annealing disregards the requested epsilon final in the slope calculation.
![anneal](https://user-images.githubusercontent.com/6538645/32686680-dc991908-c677-11e7-8eb6-8ee4cf779803.png)
Top: Current behavior, Bottom: Expected behavior

### Code to replicate
```
import matplotlib.pyplot as plt
import numpy as np
ea = EpsilonAnneal(epsilon_final=0.4, epsilon_timesteps=100)
anneal = [ea(0, x) for x in range(101)]
plt.subplot(2, 1, 1)
plt.plot(anneal)
plt.subplot(2, 1, 2)
plt.plot(np.linspace(1.0, 0.4, 100))
plt.show()
```

**Comment by AlexKuhnle** [comment]
Hey @Islandman93, you're right, actually the implementation seemed to be completely wrong (although producing sensible values for the predefined parameters). The latest commit fixed the problem, hopefully, and renamed the arguments (!!!). I haven't actually run the code, so if it's not working, please re-open.
