### ISSUE TITLE
exploration in agent.py changes type of action

### ISSUE THREAD

**Issue by xiangzhengmao** [reinforceio/tensorforce#231]
this can be reproduced with the 'FrozenLake-v0' environment
this environment takes a single integer as action
during exploration in agent.py, the line 
self.current_actions[name] = np.random.randint(low=num_actions, size=shape)
changes the type of action from 'numpy.int64' to 'numpy.ndarray' and causes a TypeError

**Comment by AlexKuhnle** [comment]
Where exactly does it cause a type error? Because NumPy arrays as return values are not unexpected --
 although I agree that it's a minor bug if the returned type is somewhat inconsistent.

**Comment by xiangzhengmao** [comment]
gym\envs\toy_text\discrete.py, line 54, in _step
    transitions = self.P[self.s][a]
TypeError: unhashable type: 'numpy.ndarray'

**Comment by xiangzhengmao** [comment]
for the same environment, prioritized_replay also fails when env.states and env.actions are directly passed as arguments
need to wrap them as dict(state=env.states) and dict(action=env.actions)

**Comment by michaelschaarschmidt** [comment]
I think the problem is this:
```
import numpy as np
type( np.random.randint(low=0, high=2, size=1))
<class 'numpy.ndarray'>
type( np.random.randint(low=0, high=2))
<class 'int'>
```
If a size argument is passed, it is always going to be an ndarray. Could check if shape is () and not pass an argument in that case but this will be moved into tensorflow anyhow soon

**Comment by michaelschaarschmidt** [comment]
https://github.com/reinforceio/tensorforce/commit/1412040a5e66e4d24932f7fc3e365ab6fb4e45ff should address this for now
