### ISSUE TITLE
Bug in model.restore function ?

### ISSUE THREAD

**Issue by ChenYingfeng** [reinforceio/tensorforce#232]
The line 976 in model.py

https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py

`        if not os.path.isfile(file):
            raise TensorForceError("Invalid model directory/file.")
`

Actually, the model file is not a full-path of a file, so need to remove this check I think, and it works well after done that.

**Comment by michaelschaarschmidt** [comment]
Fixed via https://github.com/reinforceio/tensorforce/commit/d5e46afb660379b0720d342d57371f5615916fb1

thank you for pointing it out!
