### ISSUE TITLE
CNN Max Pooling

### ISSUE THREAD

**Issue by slerman12** [reinforceio/tensorforce#235]
Is there an easy way to add max pooling to the CNN layer in the same vein as "flatten"? If not, this would be a great feature! I'm on a tight deadline and would appreciate any help with this.

Thank you so much for this amazing project!

**Comment by michaelschaarschmidt** [comment]
@AlexKuhnle can chime in but essentially need to create a small layer class and register it using
tf.layers.max_pooling2d(inputs=x, pool_size=[size, size], strides=stride)

**Comment by AlexKuhnle** [comment]
Added a `Conv2d` layer (https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/__init__.py#L24). Hope that helps.
