### ISSUE TITLE
Invalid input rank for conv2d layer: 2, must be 4

### ISSUE THREAD

**Issue by borosdenes** [reinforceio/tensorforce#239]
Hey.

This might be a dull one, but I can't really get my agent working. I'm trying to build a **VPGAgent** based on **CNN**, using **OpenAIGym** environment. My spec is as follows.

`environment = OpenAIGym(gym_id='Pong-ram-v0')`

`network_spec = [`
`      dict(type='conv2d', size=32, window=8, stride=4),`
`	dict(type='conv2d', size=64, window=4, stride=2),`
`	dict(type='conv2d', size=64, window=3, stride=1),`
`	dict(type='flatten'),`
`	dict(type='dense', size=32),`
`	dict(type='dense', size=32),`
`	dict(type='lstm', size=32)`
`]`

`agent = VPGAgent(`
`states_spec=environment.states,`
`actions_spec=environment.actions,`
`network_spec=network_spec,`
`batch_size=64`
`)`

When I try to construct VPGAgent I get the error **Invalid input rank for conv2d layer: 2, must be 4**. Same configuration seems to be able to construct agent for environment _SuperMarioBros-1-1-v0_ (even though I haven't tried running the agent so far).

Could you please explain me the error message, and also how to manage to fix that? Which configuration am I missing to set up properly? I feel like I'm missing the core idea behind this flow starting from environment throughout agent towards the network.

**Comment by AlexKuhnle** [comment]
The `Pong-ram-v0` environment uses the 1-dim RAM representation of Pong instead of the visual input, hence the rank mismatch when using convolutions. You probably meant to use `Pong-v0`.
