### ISSUE TITLE
Question about tensorboard loss calculation

### ISSUE THREAD

**Issue by borosdenes** [reinforceio/tensorforce#240]
Hey!

I'm interested in the difference between the loss function which is plotted to tensorboard via setting `summary_spec` for an agent compared to episode rewards.

I'm using OpenAIGym (Pong to be more specific), which avg. reward is starting from -21 and currently at -20. In the meantime tensorboard displays loss between -3 and -1 (increasing tendency). So far I couldn't figure out how loss is calculated, therefore can't really interpret the diagrams from tensorboard. Could you have an explanation? (Docstring documentation would've been helpful in the code here.)

_Sorry if my question is very basic, I was looking at the code before asking here -- without success._

**Comment by michaelschaarschmidt** [comment]
The loss and the reward are only vaguely related. The loss calculation is described in the respective paper and I would recommend reading RL: An introduction or a blogpost on how RL works.

**Comment by borosdenes** [comment]
Thanks for your reply! If you ment the respective paper which is linked within README.md of root, then I have to sadly remark that the link is broken (GitHub 404 error). Could you fix that link please?

**Comment by borosdenes** [comment]
Hey! Since my latest trials concerns loss calculation I'll post my issue here, and won't open another one.

I've tried to execute the **built-in examples**, without success of converge. I've checked out lateset git tag (0.3.2) beforehand. Executed following: `python examples/openai_gym.py Pong-ram-v0 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 50000 -m 2000`

I've been running this agent for 8 hours using GPU (even though which has unsignificant speed-up because of vanilla network structure), and at the end, average reward was constantly -21. I've included `summary_spec` for agent for better understanding of what's happening in the background, and loss curves seemed to be close to zero after 30 mins of training (~ 1.5M steps).

I can see that `tf_discounted_cumulative_reward` is implemented which I guess is used (according to my readings) for loss calculation. Even though I haven't found the loss which is plotted, I have no clue why doesn't the built-in example converge.

**Comment by michaelschaarschmidt** [comment]
Hello,

you have to slightly adjust your expectations with regard to how easy it is to get something to converge in reinforcement learning. The vpg.json does not have a configuration suitable for Atari games. It is just an example configuration. You need to find an effective configuration yourself, and even then VPG is a very inefficient algorithm which may take days. I recommend reading a few more examples/tutorials to understand why this is so.
