### ISSUE TITLE
SelfPlay scenario

### ISSUE THREAD

**Issue by Szpadel** [reinforceio/tensorforce#243]
Are there any plans to make Self Play scenarios possible?
Main issue is that players cannot share memory of current episode, but they should share common memory for all previous episodes.

**Comment by michaelschaarschmidt** [comment]
Hello,

this is not currently on the roadmap because it is not a typical applied problem. Memories are going to be moved into the TensorFlow graph in the upcoming weeks and that will also change things. Feel free to start on a pull request on this topic.

**Comment by michaelschaarschmidt** [comment]
Closing this as it is not part of any roadmap
