### ISSUE TITLE
Minor bug in threaded_ale.py ?

### ISSUE THREAD

**Issue by ChenYingfeng** [reinforceio/tensorforce#246]
line 90:
`agent_config = json.loads(args.agent_config)
`
This line of code  actually not works by prompting a error of "the agent_config is not a json object", 

line 93:
`
 if "exploration" in agent_config and agent_config.exploration["type"] == "epsilon_anneal":
`
it seems that we can't visit the the value "exploration" in the json string by agent_config.exploration, should be instead with agent_config[u"exploration"]

**Comment by michaelschaarschmidt** [comment]
This is a user contributed example that has not been fully tested after the new API. 

'The code of this project looks not well tested before submission. o(╥﹏╥)o' -> feel free to contribute bug fixes if you spot them

**Comment by ChenYingfeng** [comment]
@michaelschaarschmidt , sorry, I will take back what I said!

**Comment by michaelschaarschmidt** [comment]
Thank you for raising the issue anyway, we will look into it in of the next sessions -

**Comment by michaelschaarschmidt** [comment]
Updated this but cannot test it currently due to a lack of ALE setup, please re-open if it persists.
