### ISSUE TITLE
Not sure how to use distributed training

### ISSUE THREAD

**Issue by vwxyzjn** [reinforceio/tensorforce#249]
Hi,

I am trying to train the reinforcement learning agent distributedly, and it appears that [openai_gym_async.py](https://github.com/reinforceio/tensorforce/blob/master/examples/openai_gym_async.py) is an example.

Unfortunately, I was not able to understand it thoroughly. I tried to reproduce the script by using [lstm_a3c_ps.py](https://github.com/vwxyzjn/SC2AI/blob/master/micro/lstm_a3c/lstm_a3c_ps.py) and [lstm_a3c_worker.py](https://github.com/vwxyzjn/SC2AI/blob/master/micro/lstm_a3c/lstm_a3c_worker.py), but they could not run properly. 

the ``lstm_a3c_ps.py`` would run and show ``Started server with target: grpc://localhost:12222``, but once I ran ``lstm_a3c_worker.py``, both terminal show error messages.

![image](https://user-images.githubusercontent.com/5555347/33397280-32a055fa-d519-11e7-807b-5de97aca7f70.png)

It seems to me that you add the distributed setting through the following script 

```python
cluster = {'ps': ['127.0.0.1:12222'], 'worker': ['127.0.0.1:12223']}
cluster_spec = tf.train.ClusterSpec(cluster)

distributed_spec = dict(
    cluster_spec=cluster_spec,
    task_index=0,
    parameter_server=True,
    device=('/job:ps')
)

agent['distributed_spec'] = distributed_spec
```

Am I even using the ``distributed_spec`` properly? Any help would be appreciated.

**Comment by michaelschaarschmidt** [comment]
As said in gitter:

Please consider implementing an environment binding to starcraft in tensorforce so you can use our script. Otherwise we cannot know whether there is a bug in our script or in your re-implementation.
