### ISSUE TITLE
Any experience on performing multi agent learning?

### ISSUE THREAD

**Issue by cserpell** [reinforceio/tensorforce#260]
I was trying to do it with [keras-rl](https://github.com/matthiasplappert/keras-rl), but it has been hard and the project seems on hold. I will give tensorforce a try. Anybody that could share such an experience?

Anyway, I couldn't find a better place to ask. Was is the right place for questions, not necessarily as code issues?

**Comment by michaelschaarschmidt** [comment]
Well it's not quite the right place, see the readme on how to join the chat community, where you might be able todiscuss what you mean exactly
