### ISSUE TITLE
question: does tensorforce's network support combining two cnn networks?

### ISSUE THREAD

**Issue by bettermanlu** [reinforceio/tensorforce#261]
Hi,  currently I'd like to use tensorforce to implement below network(https://arxiv.org/abs/1704.04572), but as far as I know, tensorforce supports layered network simply by defining its spec file.  Does tenforforce's network support it? How to define its network spec file? Thanks a lot.
![image](https://user-images.githubusercontent.com/9689231/33744054-5575c1aa-dbea-11e7-86d0-d69c35011e3c.png)

Thanks,
-Eric

**Comment by AlexKuhnle** [comment]
Hi @bettermanlu,

You're right, we're not (currently) supporting other than layer-stack networks to be defined in a JSON format. However, you can plug in your own network by subclassing [Network](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/network.py#L30) or [LayeredNetwork](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/network.py#L141) (helps with variables, regularization losses, etc when using TensorForce layers within the more complex network) as, for instance, is done [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/base_agent_test.py#L131).

**Comment by bettermanlu** [comment]
thanks for the reply. it would be great to add an exmple to the FAQ.

**Comment by Mazecreator** [comment]
Hi @bettermanlu ,

Sorry I didn't see this before pushing the PR for the complex network.  I was going to put in an ADD layer but wanted to wait for any feedback on the approach.  Did you find a solution for your problem?  I can work on an ADD layer this week if you still need it.

**Comment by AlexKuhnle** [comment]
Oh, I haven't seen your last post, @bettermanlu, sorry for that. @Mazecreator's PR made the specification of more complex networks possible, so he knows best now. Also, the [link I posted](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/base_agent_test.py#L132) shows how to implement your own `Network` subclass and use it. If there are problems, let us know.

**Comment by michaelschaarschmidt** [comment]
This seems answered now.
