### ISSUE TITLE
Issue with running DQfD

### ISSUE THREAD

**Issue by apurvas** [reinforceio/tensorforce#263]
Hello,

I'm running DQfD using the quickstart.py guide and I'm getting the following error:

"indices = np.random.randint(self.size - 1, size=batch_size)" in core/replay.py is giving a Value Error because self.size=0 when this is called. I can seem to figure out the issue and have tried on several atari games.

The specific settings for my DQfDAgent are as follows:
agentDQFD = DQFDAgent(
        states_spec = env.states,
        actions_spec = env.actions,
        network_spec = network_spec,
        device=None,
        session_config=None,
        scope='dqfd',
        saver_spec=None,
        summary_spec=None,
        distributed_spec=None,
        optimizer=None,
        discount=0.99,
        variable_noise=None,
        states_preprocessing_spec=None,
        explorations_spec=None,
        reward_preprocessing_spec=None,
        distributions_spec=None,
        entropy_regularization=None,
        target_sync_frequency=10000,
        target_update_weight=1.0,
        huber_loss=None,
        batched_observe=1000,
        batch_size=32,
        memory=None,
        first_update=10000,
        update_frequency=4,
        repeat_update=1,
        expert_margin=0.5,
        supervised_weight=0.1,
        demo_memory_capacity=100000,
        demo_sampling_ratio=0.2)

**Comment by michaelschaarschmidt** [comment]
You have to actually insert demo observations for this to work. Please look at the dqfd test and read the paper.
