### ISSUE TITLE
Which gym version do we need to run open_universe.py example ?

### ISSUE THREAD

**Issue by gaoyuankidult** [reinforceio/tensorforce#266]
I installed gym version 0.9.3 on my system:
    gym (/home/alex/Desktop/tensorforce/gym) 0.9.3                     <pip>

After trying to run examples/openai_universe.py I received an error:

> raise error.Error("Env.configure has been removed in gym v0.8.0, released on 2017/03/05. If you need Env.configure, please use gym version 0.7.x from pip, or checkout the `gym:v0.7.4` tag from git.")

Then I switch to gym version 0.7.4 and I received an error complaining:

>  Traceback (most recent call last):
>   File "examples/openai_universe.py", line 132, in <module>
>     main()
>   File "examples/openai_universe.py", line 67, in main
>     environment.configure(remotes=1)
>   File "/home/alex/Desktop/tensorforce/tensorforce/contrib/openai_universe.py", line 119, in configure
>     self.env.configure(*args, **kwargs)
>   File "/home/alex/.conda/envs/blue-coast/lib/python3.6/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/alex/.conda/envs/blue-coast/lib/python3.6/site-packages/gym/core.py", line 349, in _configure
>     return self.env.configure(*args, **kwargs)
>   File "/home/alex/.conda/envs/blue-coast/lib/python3.6/site-packages/gym/core.py", line 230, in configure
>     reraise(suffix='(for {})'.format(self.spec.id))
>   File "/home/alex/.conda/envs/blue-coast/lib/python3.6/site-packages/gym/utils/reraise.py", line 17, in reraise
>     reraise_impl(e, traceback)
>   File "/home/alex/.conda/envs/blue-coast/lib/python3.6/site-packages/gym/utils/reraise_impl_py3.py", line 4, in reraise_impl
>     raise e.with_traceback(traceback) from None
>   File "/home/alex/.conda/envs/blue-coast/lib/python3.6/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)

gym.utils.reraise.ReraisedException: The original exception was:

Should I use a specific gym version?

-Thanks

Alex

**Comment by michaelschaarschmidt** [comment]
Which environment are you trying to run? For gym environments, use the gym example definitely, I think we have not tested universe for a while as the project has been discontinued by openAI, but if you give a specific environment/config we can try reproducing in a few days (next dev session)

**Comment by gaoyuankidult** [comment]
Thanks for the reply. I just wanted to test universe environment. 
Since the project is discontinued by openai, I think I will switch back to openai_gym.py for testing.

**Comment by michaelschaarschmidt** [comment]
Ok good, I will close this then
