### ISSUE TITLE
Explorations_spec is not recognized as the argument

### ISSUE THREAD

**Issue by sungikchoi** [reinforceio/tensorforce#268]
Hello, I am using the ALE environment and somehow have problem in the initialization

At the initialization of DQNAgent, function gets exploration_spec as the keyword.

However, when we define the DQNAgent in terms of exploration_spec, it induces error, saying that __init()__ no keyword argument of exploration_spec.

**Comment by michaelschaarschmidt** [comment]
'saying that init() no keyword argument of exploration_spec' <- are you using explorationS?
https://github.com/reinforceio/tensorforce/blob/master/tensorforce/agents/dqn_agent.py#L52

**Comment by sungikchoi** [comment]
Oh, this is just the typo. exploration_specs, and the error occurs

**Comment by michaelschaarschmidt** [comment]
Can you print the complete stack trace and are you using current master? this got updated in recent versions.

**Comment by sungikchoi** [comment]
![5a325d653fdbea95e71323c6 1](https://user-images.githubusercontent.com/20620673/33989563-4eb37800-e10b-11e7-86ac-a031c1a44310.png)
This is the error and we defined the DQNagent by 
    agent = DQNAgent(
        states_spec=environment.states,
        actions_spec=environment.actions,
        network_spec=network_spec,
        batch_size = 32,
        memory = dict(type='prioritized_replay', capacity=1000000),
        optimizer = dict(type='rmsprop', learning_rate=0.00025),
        first_update = 50000,
        explorations_spec = dict(type ='epsilon_decay', initial_epsilon = 1.0, final_epsilon = 0.1, timesteps = 1e6)
    )

**Comment by michaelschaarschmidt** [comment]
Just pushed a smaller fix, this is running for me now, although it was unrelated to your error. Latest version is ambiguous, you would need latest version from source, not latest pip install (which may be updated soon).

python threaded_ale.py breakout.bin -a configs/dqn_visual.json -n configs/cnn_dqn2013_network.json -fs 4 -ea -w 4

-->
Starting DQNAgent for Environment 'ALE(breakout.bin)'
========================================
Current Step/Episode: 0/1
SPS: 0.0
========================================
