### ISSUE TITLE
Surpport the value network and policy network share the same parameters in tensorforce?

### ISSUE THREAD

**Issue by dmuestc** [reinforceio/tensorforce#269]
Hi all, I'm a new hand at RL, tensorforce is very good for our freshes. After trying some experiments on tensorforce, I have some puzzles as follows:
1. Is the value network and policy network share the same parameters except last layer for actor critic algorithm, for example PPO?  From the code, the policy network and baseline doesn't share parameters.
2. PPO optimization uses a multi-step optimizer, repeat optimizing a same batch n-step times. According to the [paper](https://arxiv.org/abs/1707.06347), sampling a different minibatch from that batch at each optimizing step seems better?
3. Is a bug for [running_standardize.py](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/preprocessing/running_standardize.py)? It seems that tensor has no attribute "astype". maybe need to change the numpy code to tensorflow operation.

**Comment by michaelschaarschmidt** [comment]
1. You can enable this by using baseline mode ```network```
2. This will be changed again once memories have been moved into the Tensorflow graph (as opposed to python code use pure TensorFlow code), see our blogpost, before that sub-sampling from the batch does not integrate well into the new architecture.
3. Running standardize was only experimentally added recently, has not been moved into TensorFlow graph, so only normalize, standardize, grayscale, sequence, clip, divide, image_resize
are supported, but feel free to move this into the graph.

**Comment by dmuestc** [comment]
Thanks @michaelschaarschmidt reply,  I'm eager to wait for the new end-to-end architecture!
