### ISSUE TITLE
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed in runner.py

### ISSUE THREAD

**Issue by bettermanlu** [reinforceio/tensorforce#272]
Hi, 
when I tried to run my runner script with my own defined env and agent, below error occurred.
Is this an issue? How to fix it? Thanks.
-Eric

Traceback (most recent call last):
  File "qr_runner.py", line 39, in <module>
    main()
  File "qr_runner.py", line 34, in main
    runner.run(episodes=10,timesteps=10, max_episode_timesteps = 20,episode_finished=episode_finished)
  File "/home/sixilu2/github/tensorforce/tensorforce/tensorforce/execution/runner.py", line 129, in run
    (episodes is not None and self.agent.episode >= episodes) or \
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 578, in __nonzero__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

**Comment by AlexKuhnle** [comment]
This looks like an issue, I will have a look at it.

**Comment by AlexKuhnle** [comment]
You said that you have your own agent implementation? Does it re-implement any of the `reset()`, `act()`, `observe()`, `update()`? If so, then the problem probably lies there somewhere, and it would help if you share the agent's code. Also, what's your `episode_finished` function, if you have any?

**Comment by bettermanlu** [comment]
My agent and runner's github location:

https://github.com/bettermanlu/tensorforce4qr/blob/master/query_reformulator_agent.py

https://github.com/bettermanlu/tensorforce4qr/blob/master/qr_runner.py

**Comment by AlexKuhnle** [comment]
This agent doesn't look like it's implemented correctly. On the one hand, functions like `observe()` and `reset()` should call the parent methods at the end and return their values. On the other hand, the return format of the `act()` functions doesn't look right (usually an 'action' is a dict of actions).

**Comment by bettermanlu** [comment]
But from the error traceback, it is said the tf.Tensor is misused as a bool. The self.agent.episode is indeed a tensor variable, and (self.agent.episode >= episodes) is also returned as a tensor variable.  I did not quite understand how this related with the agent's incorrect implementation.
Thanks,

**Comment by AlexKuhnle** [comment]
`self.agent.episode` should not be a tensor variable, but you define it as such [here](https://github.com/bettermanlu/tensorforce4qr/blob/master/query_reformulator_agent.py#L44). Note that TensorFlow code should only appear in the `Model` implementation, according to TensorForce's current design.

**Comment by AlexKuhnle** [comment]
Closing this issue, since it seems solved.
