### ISSUE TITLE
What will be happen when I set baseline optimizer "None" but baseline model is not "None"?

### ISSUE THREAD

**Issue by dmuestc** [reinforceio/tensorforce#279]
Hi, all, 
https://github.com/reinforceio/tensorforce/blob/b32f4f55088476335e58710ec43cf84c06b5812f/tensorforce/models/pg_model.py#L268

It means that we will use only one optimizer for both policy net and baseline net, and the total loss is like: `policy_loss  + baseline_loss + c1*regularization - c2*entropy` ... ?

By the way, I do not really understand what's the function by set `batched_observe` in agent，here: https://github.com/reinforceio/tensorforce/blob/b32f4f55088476335e58710ec43cf84c06b5812f/tensorforce/agents/agent.py#L201
For update the episode counter in a batch way?

**Comment by AlexKuhnle** [comment]
Hi @dmuestc,

Indeed, if a baseline is set (`baseline_mode is not None`) but no baseline optimizer (`baseline_optimizer is None`), then optimization for policy and baseline are combined.

We introduced the `batched_observe` value for performance reasons. If set, it calls observe not for every step, but only in batches of the given size. While one of our aims is to implement all the RL logic in TensorFlow, we found that calling TensorFlow observe every timestep from Python (unsurprisingly) leads to increased runtime. Usually, however, it doesn't matter if observe is called less frequently, hence this option.

**Comment by dmuestc** [comment]
Thanks for @AlexKuhnle reply, for the first question, I can't find where the policy loss and baseline loss are combined, because when the baseline optimizer is None, the optimization is only about policy part from the code, here:
https://github.com/reinforceio/tensorforce/blob/b32f4f55088476335e58710ec43cf84c06b5812f/tensorforce/models/pg_model.py#L220
and the baseline loss are not included in `tf_optimization `. Did I understand this right, or I missed something?
Thanks~

**Comment by AlexKuhnle** [comment]
Ah, I see the confusion. If no baseline optimizer is given, the baseline loss is not used, since then the baseline is considered part of the policy loss calculation, and the baseline variables are added to the variables to be optimized in that case [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/pg_model.py#L268). So baseline optimizer given means separate baseline loss, otherwise optimization as part of the big model.
