### ISSUE TITLE
Network.py Modification from_spec()

### ISSUE THREAD

**Issue by Mazecreator** [reinforceio/tensorforce#285]
I see an update to network.py in the from_spec() static method.

It isn't clear to me why this structure has an else:
https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/network.py#L150

In the else, this should simply be a failure as it doesn't match either the Complex or Layered network specification.  I am sure the else will fail to create a network object and then fail the assert, but seems like a  complex way to raise an error.

**Comment by michaelschaarschmidt** [comment]
The from_spec method failed for custom networks which are not passed as lists of dicts or lists of objects.

Try it for yourself by removing the else and running:
python -m unittest tests.test_vpg_agent.TestVPGAgent.test_multi

**Comment by Mazecreator** [comment]
I believe it catches those problems, just seems like it is strange to pass something that is known to be invalid into util.get_object() method.  In the Else clause, you know the get_object will fail... could be replaced with:
network = None

or raise an error directly.

**Comment by michaelschaarschmidt** [comment]
Why is it invalid? This is not a fail. Network is returned as the custom network passed in spec.

**Comment by Mazecreator** [comment]
Sorry, guess I just don't understand what you mean by a custom network.  I looked at the "test_vgp_agent" and don't see any sort of network_spec passed.  I Didn't know that is how to passed that into the code.  I don't know the full structure behind the test, so if you need this for Custom that is fine.  I looked in the Blog too and couldn't find any spec on how to pass the custom networks.

**Comment by Mazecreator** [comment]
We probably need a "network_spec.md" doc as well... I might be able to start one with the Layered and Complex, but not sure how the Custom blends into it.

**Comment by michaelschaarschmidt** [comment]
In general it's a good idea to run all tests to identify these errors:
https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/base_agent_test.py#L202

We create a custom network here and pass it. 

from_spec checks whether it's a list and then parses it either as a complex or standard network. If it's not a list, we let util.get_object do the work of inspecting what spec is, in the case of an instantiated object that is returned, so network is simply the object that was passed in because get_object has nothing to do. 

Yes an md might be good, see the test lines I linked, you simply extend the network class and create whatever you want.

**Comment by Mazecreator** [comment]
Thanks, I will start a network_spec in the next few days.  It will likely need more details for the Custom Network as I don't know all the details but can put in a few pointers that you have here.

**Comment by michaelschaarschmidt** [comment]
Ok great, I will close this then - thanks for contributing

**Comment by AlexKuhnle** [comment]
FYI: The `get_object` method is used throughout the framework and supports various mechanisms, via specification dicts or not, relying on a default class (as is commonly the case for networks, but by far not the only way), predefined classes via labels, full module paths, passed class objects, or even instantiated objects. Even if one way is common, it should always go via this general procedure. In this case it's just about setting the default class differently in case of a specific short-form input structure (lists of lists).
