### ISSUE TITLE
Problems Saving Model with agent.save_model

### ISSUE THREAD

**Issue by arjunneervannan** [reinforceio/tensorforce#287]
I am implementing Tensorforce with the HalfCheetah-v1 environment in OpenAI. I was able to get the model to start learning using the sample code, but I am having some trouble using the agent.save_model and the agent.restore_model functions. I was able to get the program to start the learning, but I wanted to actually see the progress at the end of the learning period. I decided to save the model every 100 episodes using the below line of code (I have a folder named "models" in which I want to save my model files): 

`agent.save_model(directory=os.getcwd() + "/models")`

I ran the program for 100 episodes. However, when I checked the models folder, I did not find anything, but I did find 3 files in the current directory, named models-20100.data-00000-of-00001, models-20100.index, models-20100.meta. In addition, the agent.restore_model function did not run because it did not find any files in the specified folder.

I also tried using:

`agent.model.save_model(path=path, use_global_step=False)`

But I got the following error:

`AttributeError: 'PGProbRatioModel' object has no attribute 'save_model'`

I also tried directly saving the model to a separate .ckpt file that I had already made named model.ckpt, but I still got the same three files stated above, and the .ckpt file remained empty.

My tensorforce version number is 0.3.3, and my tensorflow-gpu version number is 1.4.1.

**Comment by michaelschaarschmidt** [comment]
So I just tried locally:
self.agent.save_model(directory=os.getcwd())

This creates a file for me called 'checkpoint' and the data, index and .meta files. Please verify if this file 'checkpoint' exists somewhere. If you then call restore model without a file given, it will use the checkpoint file to read from the other files, no .ckpt file is needed.

**Comment by arjunneervannan** [comment]
I am getting the 'checkpoint' file along with the other three files, but it is not saving it in the correct directory. I set it to save in the tensorforce-master/examples directory, but it saves it in tensorforce-master itself. I am only using `agent.save_model(directory=os.getcwd)`; no string concatenation.

**Comment by michaelschaarschmidt** [comment]
Maybe print os.getcwd and make sure you are getting the right path, alternatively explicitly specify the full absolute path to the directory you want?

**Comment by arjunneervannan** [comment]
The file was created in the correct directory. I used the following lines of code to save the model:
`modelDir=os.path.join(os.getcwd(), "models")
agent.save_model(directory=os.path.join(modelDir, "agent"))
saved_agent = agent.restore_model(os.path.join(modelDir, "checkpoint"))`
This worked to save the checkpoint file as well as the other three files. However, when I tried to load it, it returned with `ValueError: Can't load save_path when it is None.`. I checked the path, and the file is there. Do I have to put a file extension on the checkpoint file (like checkpoint.ckpt)?

**Comment by arjunneervannan** [comment]
I wasn't sure if it was looking for the file 'checkpoint' or the folder in which it was in. The agent.save_model seems to be creating the files, but the agent.restore_model is throwing an error: `RuntimeError: Attempted to use a closed Session.`. 

I am trying to visualize the trained model after it is done learning. Here is the code that does so:

`saved_agent = agent.restore_model(os.path.join(modelDir))`
`env = gym.make("HalfCheetah-v1")`
`s = env.reset()`
`done = False`
`while not done:`
        `env.render()`
        `action = saved_agent.act(s)`
        `s, r, done, _ = env.step(action)`

**Comment by AlexKuhnle** [comment]
I haven't looked into the problem yet, but could you check two things: First, if you restore the model, I don't think you have to specify the checkpoint (here: `agent.restore_model(os.path.join(modelDir, "checkpoint"))`). Second, the agent is not returned as a separate `saved_agent` value in `saved_agent = agent.restore_model(os.path.join(modelDir))`, but you create the agent via `agent.Agent(...)` and then call `agent.restore_model(...)` on it.

**Comment by arjunneervannan** [comment]
I redefined the agent again as `agent007`, like so:
` agent007 = Agent.from_spec(`
        `spec=agent_config,`
        `kwargs=dict(`
            `states_spec=environment.states,`
           ` actions_spec=environment.actions,`
            `network_spec=network_spec`
       ` )`
   ` )`
and instead of doing `saved_agent = agent007.restore_model(modelDir)`, I did `agent007.restore_model(modelDir`. That seemed to work, and the model is being rendered now. Thanks for the help!

**Comment by michaelschaarschmidt** [comment]
Ok, great - I will close this now then.

**Comment by lefnire** [comment]
@arjunneervannan could you perchance post the code you got working? I'm having a similar issue here. 

There's something a bit off on the path setup. If I say `agent.save_model(os.path.join(os.getcwd(), "saves", "test"))`, it doesn't save to a `saves/test/` directory, but instead saves `saves/test-*` files; even if `saves/test/` exists, and though `save_model`'s first arg is `directory`. Then `agent.restore_model()` seems to behave a different way. Can't seem to get them to agree.

**Comment by lefnire** [comment]
Oh I got it. `save_model` wants `path/file` (`file` will be used as multiple `file-*` files), and `restore_model` wants `path`.

```python
directory = os.path.join(os.getcwd(), "saves", "my_agent")
file = os.path.join(directory, "anything")  # used for `anything-*`, I just use "my_agent" again
...
agent.save_model(file)
...
agent.restore_model(directory)
```

**Comment by michaelschaarschmidt** [comment]
Would be useful to add as a faq entry at some point soon

**Comment by AlexKuhnle** [comment]
Can you post the lines of code for saving/loading? Is the model stored in the path you specify, i.e., are there the expected files?

**Comment by mrbeann** [comment]
> Can you post the lines of code for saving/loading? Is the model stored in the path you specify, i.e., are there the expected files?

Thanks, I fix it. It's due to tensorflow version.

**Comment by AlexKuhnle** [comment]
Great!

**Comment by ihtisham0331** [comment]
> > Can you post the lines of code for saving/loading? Is the model stored in the path you specify, i.e., are there the expected files?
> 
> Thanks, I fix it. It's due to tensorflow version.
WHICH VERSION OF TENSORFLOW YOU USED?

**Comment by AlexKuhnle** [comment]
The latest version of Tensorforce is now using TensorFlow 2.0. Until very recently, for the last months the TensorFlow version was 1.13.1.
