### ISSUE TITLE
Timeout for HalfCheetah-v1?

### ISSUE THREAD

**Issue by arjunneervannan** [reinforceio/tensorforce#288]
I am running the HalfCheetah-v1 environment and noticed that, on the website, the passing score was 4800. My algorithm does run, but the score is only about 500 or 600. I'm guessing that the reason for this is that the timeout is too short, so it's not running for long enough to be able to receive a reward of 4800. Does anyone know the episode timeout that the OpenAI Gym environment uses? See [this](https://gym.openai.com/envs/HalfCheetah-v1/) for more details.

**Comment by AlexKuhnle** [comment]
We haven't played around with environments like HalfCheetah-v1 etc, and I'm not sure how many other users are reading issues, so it might be best to ask such a question in the Gitter community channel, for which you can sign up [here](https://docs.google.com/forms/d/1_UD5Pb5LaPVUviD0pO0fFcEnx_vwenvuc00jmP2rRIc/).

**Comment by arjunneervannan** [comment]
Thanks, I will take a look there.
