### ISSUE TITLE
Utilizing GPU Capabilities

### ISSUE THREAD

**Issue by arjunneervannan** [reinforceio/tensorforce#290]
I am running the example program on a GPU Linux computer for 30,000 episodes on the Half-Cheetah model as well as some other walking environments from MuJoCo. I ran the same program on a MacBook Pro, and it took the same time to train the same number of episodes. I have the latest version of tensorflow-gpu installed, and when I checked the GPU performance using the nvidia-smi command, and it seems to be using it. How can I ensure that the computer is using its full GPU capabilities?

**Comment by AlexKuhnle** [comment]
The problem with GPU utilization for reinforcement learning is that a lot of the time is spent on retrieving actions, which is an unbatched TensorFlow call and consequently GPUs have little effect of speeding this up. The biggest effect of GPUs is expected for the batched and more complex update calls. A difference is probably that policy gradient models update comparatively infrequently, hence less acceleration, while memory-based Q models perform updates more frequently, hence potentially more acceleration. I assume you ran it with a policy gradient model? That might be why the effect is practically non-existent.

We do not currently have a good way of improving this, but version 0.4 or 0.5 will focus on distributed execution etc, which helps to get the most out of your GPU. If you find indicators that indeed your GPU is not utilized at all, please reopen this issue.
