### ISSUE TITLE
Activation for mlp2?

### ISSUE THREAD

**Issue by arjunneervannan** [reinforceio/tensorforce#291]
I did not find any activation function defined on the mlp2.json network (in the configs folder). Is there a default activation function that the network takes if nothing is specified?

**Comment by devnag** [comment]
Yes, if you look at the [Dense class](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/layer.py#L508), it has 'tanh' as the default activation when none is specified.


These kinds of questions are better answered at the Gitter: https://gitter.im/reinforceio/TensorForce

**Comment by michaelschaarschmidt** [comment]
Great answer, I would also request that you read the FAQ for the general stance on support.
