### ISSUE TITLE
Exploration out of bounds

### ISSUE THREAD

**Issue by amitrack** [reinforceio/tensorforce#297]
Hello,
I've noticed that the action values put with any(all?) exploration modes with a float action space flows below/above min_value/max_value, is there an issue ?

**Comment by michaelschaarschmidt** [comment]
Was there no issue in the end or why did you close the issue?

**Comment by AlexKuhnle** [comment]
This would be an issue, since it should be clipped accordingly [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L809), so let us know if bound float actions are indeed exceeding bounds for exploration.

**Comment by amitrack** [comment]
I was using an older version of tensorforce, installed the lastest version of the repo and it stopped outputting out of bounds actions. Sorry. My bad.
