### ISSUE TITLE
Make Gaussian initial std configurable

### ISSUE THREAD

**Issue by michaelschaarschmidt** [reinforceio/tensorforce#30]
From https://github.com/reinforceio/tensorforce/issues/26:

'Another thing I noticed in continuous state spaces is that the standard deviation of the Gaussian (exploration) noise is not parameterized. That seems like a bad default for this kind of on-policy method. It's an easy fix since the required code in the Gaussian class is just commented out, but enabling this does not seem possible without low-level adjustments at the moment.'

**Comment by michaelschaarschmidt** [comment]
Further issue:

Another thing that might be nice to add to the library is the ability to query the action without any exploration noise. This could come, for example, in the form of an exploration=True keyword in agent.act(). In the case where the policy is stochastic this could boil down to evaluating the mean model, which would require some minor internal changes.

**Comment by AlexKuhnle** [comment]
Both integrated.
