### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#301]
Still getting the seg-fault crash. 
- TensorForce: 4b5741d2088869e7f8f40c354bd63762c8d62833 (master)
- TensorFlow: v1.5.0-rc0, compiled from source on Ubuntu (CPU-only; setting up GPU now and will report back)

`Segmentation fault (core dumped)`

LMK if there's some way I can dig further, very basic error. Also LMK if I should try a different TensorFlow version (v1.5.0-rc1, master, etc)

**Comment by michaelschaarschmidt** [comment]
Just to make sure, pip install does not get the error (we are mostly working on the pip versions for dockerization)?

**Comment by michaelschaarschmidt** [comment]
Also, what ubuntu version? Seems like they are doing their builds on 16.04 now and backwards compatibility with 14.04 will not be guaranteed due to cuda.

**Comment by lefnire** [comment]
pip install of tensorforce, right? (not tensorflow? which is 1.4.x). Ubuntu 17.10, should I try 16.04?

**Comment by michaelschaarschmidt** [comment]
Pip install of TensorFlow, TensorForce master should be good

**Comment by lefnire** [comment]
All's well on `pip install -I tensorflow==1.5.0rc0` (and I'm assuming `pip install tensorflow` since that's _less_ pushy), thanks for talking me through it!

**Comment by michaelschaarschmidt** [comment]
Ok great - I am not too certain about what can go wrong in the 'from source' installs and all the different options (I suspect if you select an option that is incompatible with your OS/build things go wrong).

**Comment by lefnire** [comment]
I figured it'd be a safe bet, pretty vanilla: c5 AWS instance, Ubuntu 17.10 (official AMI), all the default options in `./configure`. But seems even so, source is too per-system for comfort.

**Comment by michaelschaarschmidt** [comment]
At some point in the near future when we focus purely on performance (in about a month or so) we will look into it and see if there is a deeper issue
