### ISSUE TITLE
Exploration tied to action sampling for DQN agent

### ISSUE THREAD

**Issue by watterm** [reinforceio/tensorforce#306]
Hey,

the `deterministic` parameter in `Agent.act` controls both exploration and action sampling. I was confused why my training performance with epsilon = 0 for a DQN agent was worse than validation performance. The problem is that without specifying `distributions_spec` the parent class DistributionAgent defaults to a categorical distribution for discrete action spaces, which then samples the actions instead of taking the argmax. I don't think this should happen for DQN (unless specified), but found no way to change it through configurations.

For my stuff, I hacked together a subclass to the categorical distribution which always calls `tf_sample` in the deterministic setting. If I use this with `distributions_spec`, it works as expected, but I don't know if that's a suitable solution for the framework.

**Comment by AlexKuhnle** [comment]
The way it works now is that some models (policy-gradient-based models) implicitly sample actions, while others (q-value-based models) choose actions deterministically. The deterministic flag turns off exploration for all models, and additionally turns off sampling for the former type of models. We think that this way it makes most sense (in the context of the library), at least for now.
