### ISSUE TITLE
Intermittent missing index in prioritised reply

### ISSUE THREAD

**Issue by mryellow** [reinforceio/tensorforce#308]
No idea how to duplicate but have had this one come up twice recently.

Perhaps something which changed in the last 6 months too as only had issues after pulling upstream.

I notice this commit plays with initialisation of variables.

https://github.com/reinforceio/tensorforce/commit/7deceb39597ea90e0f130448cf3616f0875b7f91#diff-2dd448622e0419a4b357148dd19fae7a

While this has a backup of an older implementation.

https://github.com/reinforceio/tensorforce/commit/e6e5b60abe95a6177e7e1a57fb8507b09244fb07#diff-2dd448622e0419a4b357148dd19fae7a

```
Traceback (most recent call last):
  File "examples/openai_gym.py", line 139, in <module>
    main()
  File "examples/openai_gym.py", line 131, in main
    episode_finished=episode_finished
  File "/home/yellow/src/tensorforce_fork/tensorforce/execution/runner.py", line 127, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/yellow/src/tensorforce_fork/tensorforce/agents/memory_agent.py", line 136, in observe
    batch = self.memory.get_batch(batch_size=self.batch_size, next_states=True)
  File "/home/yellow/src/tensorforce_fork/tensorforce/core/memories/prioritized_replay.py", line 264, in get_batch
    observation, _ = self.observations._memory[index]
TypeError: 'int' object is not iterable
```

**Comment by michaelschaarschmidt** [comment]
Hey, thank for notifying us, although just as a heads-up we will probably just re-implement prioritised replay in the new branch

**Comment by mryellow** [comment]
Seems to happen on episode 133 of length 100 steps, after the initial filling of memory I guess.

```
"memory": {
        "type": "prioritized_replay",
        "capacity": 100000
    },
```

**Comment by AlexKuhnle** [comment]
This feature was contributed by @wassname, so if he could comment on that, would be great. It seems like the content of `self._memory` is inconsistent and something is not updated correctly, or so...

**Comment by wassname** [comment]
The first half of the sumtree has integers (representing summed priority), the second half has (item, priority) pairs. So it looks like it's trying to access the wrong half,  so it's reference the int instead of the tuple. If it happens after filling up, the self._memory.observations._position is too low.

Perhaps [this line](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/memories/prioritized_replay.py#L113) is wrong.

It's hard to debug without replicating, do you think you could share your setup?

**Comment by mryellow** [comment]
> replicating

It's a private environment unfortunately but perhaps I can duplicate with CartPole or something. Is intermittent so will hammer it a few times later and see if the same error comes up.

**Comment by wassname** [comment]
Yeah maybe it will still happen if you plug in CartPole, decrease memory size, and run with the same setup?

**Comment by mryellow** [comment]
>  decrease memory size

Have tried a few configurations and no hits yet. 

One thing about my setup is `-m 100` for a limit of 100 steps per episode. Has me thinking that perhaps it's something to do with that modulus at https://github.com/reinforceio/tensorforce/blob/d03f7862aec3fce5ed0a3e1ea8d775992476da98/tensorforce/core/memories/prioritized_replay.py#L115. Perhaps my number of timesteps was fitting perfectly within a modulus which then causes an off-by-one error or something.

Experimenting with similar limits on CartPole.

**Comment by wassname** [comment]
Yeah that seems like a likely culprit. If you want to debug it yourself you can stop at the exception, and go check the values of `self._memory.observations._position` as well as _capacity etc.

**Comment by michaelschaarschmidt** [comment]
Prioritized replay now implemented in tensorflow so closing this
