### ISSUE TITLE
setup.py and tensorflow with/without gpu

### ISSUE THREAD

**Issue by pedronahum** [reinforceio/tensorforce#31]
Hi,

Unless the goal is not to support tensorflow with gpu, I would recommend to move the tensorflow requirement to "extra_requires".  I have seen this pattern in both sonnet and tensor2tensor. 

For example:

extra_packages = {
    'tensorflow': ['tensorflow>=1.0.1'],
    'tensorflow with gpu': ['tensorflow-gpu>=1.0.1']
}

install_requires=[
          'numpy',
          'six',
          'scipy',
          'pillow',
          'pytest'
      ]

setup_requires=['numpy', 'recommonmark', 'mistune']

setup(name='tensorforce',
      version='0.2',
      description='Reinforcement learning for TensorFlow',
      url='http://github.com/reinforceio/tensorforce',
      author='reinforce.io',
      author_email='contact@reinforce.io',
      license='Apache 2.0',
      packages=['tensorforce'],
      install_requires=install_requires,
      extra_requires=extra_packages,
      setup_requires=setup_requires,
      zip_safe=False)

Regards,

Pedro

PS Will spend my weekend understanding tensorforce. Great work!

**Comment by michaelschaarschmidt** [comment]
Good point, we will get to this, thanks!

**Comment by pedronahum** [comment]
Hi,

Apologies for re-opening the issue. The current setup.py will fail to recognize if tensorflow-gpu is already installed. In fact, it would download and install the cpu version.  

If I make the changes as shown below, would allow the following installation options:

# Assumes tensorflow or tensorflow-gpu installed
pip install tensorforce -e .

# Installs with tensorflow-gpu requirement
pip install tensorforce[tf_gpu] -e .

# Installs with tensorflow (cpu) requirement
pip install tensorforce[tf] -e .

setup(name='tensorforce',
      version='0.2',
      description='Reinforcement learning for TensorFlow',
      url='http://github.com/reinforceio/tensorforce',
      author='reinforce.io',
      author_email='contact@reinforce.io',
      license='Apache 2.0',
      packages=['tensorforce'],
      install_requires=[
    	'numpy',
    	'six',
	'gym>=0.7.4',
    	'universe>=0.21.3',
	'scipy',
    	'pillow',
    	'pytest'
	],
      setup_requires=[
    	'numpy',
    	'recommonmark'
	],
      extras_require={
    	'tf': ['tensorflow>=1.2.0'],
    	'tf_gpu': ['tensorflow-gpu>=1.2.0'],
	},
      zip_safe=False)

I guess I am very motivated to use the library :o)

Thanks,

Pedro

**Comment by krfricke** [comment]
Sorry, I forgot to remove tensorflow from the install_requires list when I added the extras_require dict. I pushed an update in f4fa33cdeee5e36b5d0bbbfe0ae5e4304631ad59. I currently can't confirm it fixes the issue as I don't have tensorflow-gpu installed. It would be great if you could check if the commit solves the issue.

**Comment by pedronahum** [comment]
Hi,

Confirmed! And the following 3 options are still valid:

--Assumes tensorflow or tensorflow-gpu installed
pip install tensorforce -e .

--Installs with tensorflow-gpu requirement
pip install tensorforce[tf_gpu] -e .

--Installs with tensorflow (cpu) requirement
pip install tensorforce[tf] -e .

Maybe it is worth to update the installation instructions as well...

Thanks!

**Comment by krfricke** [comment]
I will add some instructions to the readme. Thanks for your help, Pedro!
