### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run'

### ISSUE THREAD

**Issue by joshland96** [reinforceio/tensorforce#311]
I get this error when trying to call the run method of the Runner object in a loop (the goal is to automate training of a model with different networks). I'm using the PPO agent and very basic network architectures. This occurs both with the Bipedal Walker env and my own custom env. 

```
Traceback (most recent call last):
  File "run_all.py", line 46, in <module>
    run_agent(agent)
  File "run_all.py", line 22, in run_agent
    runner.run(episodes=10000, max_episode_timesteps=300, episode_finished=episode_finished)
  File "/Users/Josh/anaconda/lib/python2.7/site-packages/tensorforce/execution/runner.py", line 77, in run
    self.agent.reset()
  File "/Users/Josh/anaconda/lib/python2.7/site-packages/tensorforce/agents/agent.py", line 150, in reset
    self.episode, self.timestep, self.next_internals = self.model.reset()
  File "/Users/Josh/anaconda/lib/python2.7/site-packages/tensorforce/models/model.py", line 992, in reset
    episode, timestep = self.monitored_session.run(fetches=(self.episode, self.timestep))
  File "/Users/Josh/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    return self._sess.run(fetches,
AttributeError: 'NoneType' object has no attribute 'run'
```

I've seen a similar issue in Tensorflow: [https://github.com/tensorflow/tensorflow/issues/8652](url). Has anyone else encountered this before? Any help is appreciated.

**Comment by AlexKuhnle** [comment]
If I understand correctly, you're not re-initializing the `Runner` (and hence the `Agent` and `Environment`) after every iteration? In that case, if there are no reasons to do otherwise, I would suggest initializing everything from scratch for every iteration.

(We will probably look into this and whether we want to make things a bit more flexible, but it's not very high on the to-do list, so if you're keen to look into it, we would welcome a PR. That is, if indeed my suggested fix helps.)

**Comment by joshland96** [comment]
Thanks for the feedback! I will try that and get back to you with the results soon.

**Comment by AlexKuhnle** [comment]
Closing the issue, assuming the suggestion solves the problem. Please re-open if not...

**Comment by sumitappsbee** [comment]
Hello, I am also facing the same issue can someone give me any feedback on what to do...
Traceback (most recent call last):
  File "~/FaceNet-IOT-master/IOT-FaceReco.py", line 219, in <module>
    main(sys.argv)
  File "~/FaceNet-IOT-master/IOT-FaceReco.py", line 49, in main
    facenet.load_model('/home/appsbee/PycharmProjects/Face_recognizer/facenet/facenet-master/src/models/facenet2/20180912-115718/')
  File "~/src/align/facenet.py", line 385, in load_model
    saver.restore(tf.get_default_session(), os.path.join(model_exp, ckpt_file))
  File "~/python/training/saver.py", line 1724, in restore
    sess.run(self.saver_def.restore_op_name,
AttributeError: 'NoneType' object has no attribute 'run'

**Comment by AlexKuhnle** [comment]
Hi, did the above not help? Also, are you even using TensorForce (considering the exception is thrown here `File "/src/align/facenet.py", line 385, in load_model` and then here `File "/python/training/saver.py", line 1724, in restore`?
