### ISSUE TITLE
Save/load model manually

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#313]
TForce currently uses `tf.train.Saver` w/ `saver_spec` to automatically save per x steps or seconds, which is super slick. It would be nice to also be able to save manually. Looks like such was [intended at some point](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/agents/agent.py#L197), but I've used that code without success (IIRC from a Gittr convo, it's stale & unsupported, right?) I'd be willing to PR it up-to-shape, but not familiar with its play-in with `tf.train.Saver`... any pointers? (Or I'll leave it to y'all if you know the quickie).

Example manual-saving scenario: auto early-stopping during training. 

```
if curr_score > last_score and last_score > min_threshold: 
  agent.save_model()
else:
  kill()
```

**Comment by michaelschaarschmidt** [comment]
https://github.com/reinforceio/tensorforce/issues/287 I have tried that recently and it worked then..

**Comment by lefnire** [comment]
sorry, must be user error then! I'll give that a go & report back
