### ISSUE TITLE
[FR] Add AlphaZero algorithm

### ISSUE THREAD

**Issue by WojciechMigda** [reinforceio/tensorforce#315]
Hi,
AlphaZero is another RL algorithm from Google. Does it fit to be included in tensorforce?
https://medium.com/applied-data-science/how-to-build-your-own-alphazero-ai-using-python-and-keras-7f664945c188 (with more links inside)
Thanks,

**Comment by michaelschaarschmidt** [comment]
Hello,

this is very unlikely to be added by us because it's particular to certain games and not a generally useful feature. It would only be added if someone fully contributed it as an example

**Comment by AlexKuhnle** [comment]
Closing the issue, since this is not on the roadmap any point soon. (PR of course very welcome, and happy to answer questions along the way...)
