### ISSUE TITLE
How to use custom preprocessor in Agent?

### ISSUE THREAD

**Issue by Garrus007** [reinforceio/tensorforce#316]
I want to implement custom Preprocessor. 
How can I use it in pre-build Agent, such as `PPOAgent`? Agent get `states_preprocessing_spec` argument, so Preprocessors Stack should be described as a config object. But inner code can build Preprocessor Stack from config if only  preprocessor type is in `preprocessors` dict from `tensorforce.core.preprocessing.__init__.py`.

**Comment by AlexKuhnle** [comment]
Hi @Garrus007,

It should also accept other values, so if you e.g. pass `dict(type='your_module.YourPreprocessor', ...args...)` or `dict(type=your_module.YourPreprocessor, ...args...)` or even `dict(type=your_module.your_module.YourPreprocessor(...args...))`, this should work. Let us know if it does not...

**Comment by Garrus007** [comment]
So, I should modify `tensorforce/core/preprocessing/__init__.py` and reference my custom preprocessor?

**Comment by AlexKuhnle** [comment]
No, what I mean is that you should be able to specify your own preprocessor via the config / arguments, e.g.:  `VPGAgent(..., states_preprocessing_spec=dict(type='your_module.YourPreprocessor', ...), ...)`.

**Comment by Garrus007** [comment]
O, thanks. It's work.
When I testing my prerpocessor, it was in same file with main code, so I tried to just pass 
```python
preprocessing_config = [
    {
        "type": "MyPreprocessor",
    }
]
```
to `states_preprocessing_spec` and It didn't work.

I've moved preprocessor to a different module and pass `my_module.MyPreprocessor` and it's works.

**Comment by AlexKuhnle** [comment]
Great, let us know if you encounter other problems.
