### ISSUE TITLE
Multiple states 

### ISSUE THREAD

**Issue by corentinmarek** [reinforceio/tensorforce#319]
Hey guys, thanks for the good work on this project. 

Not necessarily a bug but I did not find a better place to ask my question as you don't seem to be active on stackoverflow. 
Here is my problem. The project README says we can use multiple state inputs. However, when I run this: 
```
agent = PPOAgent(
    states_spec={
     'state1': dict(type='float', shape=(1,)),
     'state2': dict(type='float', shape=(1,))
    },
    actions_spec=dict(type='int', num_actions=10),
    network_spec=[
        dict(type='dense', size=64),
        dict(type='dense', size=64)
    ],
    batch_size=1000,
    step_optimizer=dict(
        type='adam',
        learning_rate=1e-4
    )
)
```

I get the following error stack:
```
~/venv/lib/python3.4/site-packages/tensorforce/models/model.py in create_output_operations(self, states, internals, actions, terminal, reward, update, deterministic)
   1107             internals=internals,
   1108             update=update,
-> 1109             deterministic=deterministic
   1110         )
   1111         self.fn_loss_per_instance(

~/venv/lib/python3.4/site-packages/tensorflow/python/ops/template.py in __call__(self, *args, **kwargs)
    276           custom_getter=self._custom_getter) as vs:
    277         self._variable_scope = vs
--> 278         result = self._call_func(args, kwargs, check_for_new_variables=False)
    279         self._variables_created = True
    280         return result

~/venv/lib/python3.4/site-packages/tensorflow/python/ops/template.py in _call_func(self, args, kwargs, check_for_new_variables)
    215           ops.get_collection(ops.GraphKeys.TRAINABLE_VARIABLES))
    216 
--> 217       result = self._func(*args, **kwargs)
    218       if check_for_new_variables:
    219         trainable_variables = ops.get_collection(

~/venv/lib/python3.4/site-packages/tensorforce/models/distribution_model.py in tf_actions_and_internals(self, states, internals, update, deterministic)
    143 
    144     def tf_actions_and_internals(self, states, internals, update, deterministic):
--> 145         embedding, internals = self.network.apply(x=states, internals=internals, update=update, return_internals=True)
    146         actions = dict()
    147         for name, distribution in self.distributions.items():

~/venv/lib/python3.4/site-packages/tensorflow/python/ops/template.py in __call__(self, *args, **kwargs)
    276           custom_getter=self._custom_getter) as vs:
    277         self._variable_scope = vs
--> 278         result = self._call_func(args, kwargs, check_for_new_variables=False)
    279         self._variables_created = True
    280         return result

~/venv/lib/python3.4/site-packages/tensorflow/python/ops/template.py in _call_func(self, args, kwargs, check_for_new_variables)
    215           ops.get_collection(ops.GraphKeys.TRAINABLE_VARIABLES))
    216 
--> 217       result = self._func(*args, **kwargs)
    218       if check_for_new_variables:
    219         trainable_variables = ops.get_collection(

~/venv/lib/python3.4/site-packages/tensorforce/core/networks/network.py in tf_apply(self, x, internals, update, return_internals)
    251         if isinstance(x, dict):
    252             if len(x) != 1:
--> 253                 raise TensorForceError('Layered network must have only one input, but {} given.'.format(len(x)))
    254             x = next(iter(x.values()))
    255 
```
My understanding is a LayeredNetwork can not take care of the aggregation of the states by itself, and only expect a single tensor input. However, I can't figure where to specify how to merge the states input. 

Thanks for your help.

**Comment by AlexKuhnle** [comment]
Hi @corentinmarek,

You're right, our current network spec interface can only handle single states. In your case I would suggest just combining the two states and let the environment handle the rest, so `dict(type='float', shape=(2,))`. This is effectively the same as merging them before passing them on to the network (which doesn't exist as option). For your information: There is also the recently contributed feature of 'complex networks' which can handle arbitrary many input states, and there is the possibility to define your own network as TensorFlow code instead of via a `network_spec` list object. The easiest way in your case, however, seems to be to just concatenate the two states...

**Comment by corentinmarek** [comment]
Ok @AlexKuhnle,  I will experiment with the ComplexNetwork I think. 
Also, do you guys have any public plan regarding next features / api changes ? I am just getting familiar with the code base right now, but I would be keen to help eventually so it would help to know what you are heading for. 
Thanks again!

**Comment by AlexKuhnle** [comment]
Kind of... The 'memory' branch is public and contains a few fundamental changes. Then there are various smaller specification/model generalizations and some additional features for existing classes that will likely follow in the next weeks. The next big topic after the 'memory' branch is complete and merged is execution. Best join our [Gitter chat](https://docs.google.com/forms/d/1_UD5Pb5LaPVUviD0pO0fFcEnx_vwenvuc00jmP2rRIc/) if you want to get more involved. :-)

**Comment by corentinmarek** [comment]
Thanks for the answers. Closing the PR.
