### ISSUE TITLE
Fix model.py for distributed_spec runs

### ISSUE THREAD

**Issue by sven1977** [reinforceio/tensorforce#321]
Please move the line:
`global_variables = list(set(global_variables))` (models.py:444)

(https://github.com/reinforceio/tensorforce/blob/f1c49de35633ad5b6866834200df75bd2b2dfc1c/tensorforce/models/model.py#L444)

out of the if-else block (move two lines lower + unindent it). That will fix an error message coming from tf.train.Saver when running with distributed-spec != None.

**Comment by michaelschaarschmidt** [comment]
Thanks for raisin it, will do on the weekend

**Comment by michaelschaarschmidt** [comment]
Done, should be fine now
