### ISSUE TITLE
Model for the Memory Agent

### ISSUE THREAD

**Issue by bching28** [reinforceio/tensorforce#323]
Hi,

Just wondering, is there a particular model that can be used to initialize the MemoryAgent or are we expected to create our own model?  I don't see a current model that can handle the batch_size, first_update, update_frequency, and repeat_update variables.

**Comment by AlexKuhnle** [comment]
Hi @bching28,

`Model`s in TensorForce are objects that an `Agent` internally uses and which implements most of the actual code (in TensorFlow), while `Agent`s are essentially 'wrappers' specifying what arguments/hyperparameters etc are available and initializes its `Model` object accordingly. So there is no `Model` inheriting from `MemoryAgent`, but there are various `Agent` subclasses, for instance `DQNAgent` [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/agents/dqn_agent.py#L25) or more or less all "Q-agents". The `Model` in the current version doesn't take care of update scheduling and memory. Note, however, that we're about to release an update, where this functionality is also moved to the `Model` subclasses (and hence to TensorFlow code).

I think this answers the question, hence closing the issue, re-open if not.
