### ISSUE TITLE
cannot import Configuration

### ISSUE THREAD

**Issue by smasoudn** [reinforceio/tensorforce#331]
I am following the documentation [here](http://reinforce.io/blog/introduction-to-tensorforce/) and in the first line (`from tensorforce import Configuration`)  I keep getting:

    ImportError: cannot import name Configuration

I tried both 0.3.2 and 0.3.5 versions. Has `Configuration` been deprecated? If so, where can I find the updated documentation?

Thanks,

**Comment by AlexKuhnle** [comment]
Yes, `Configuration` does not exist anymore. Instead of passing this object, the arguments are now passed directly to the agent, check out the `DQNAgent`, for instance ([here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/agents/dqn_agent.py)).

**Comment by AlexKuhnle** [comment]
Another example of an actual agent being instantiated is [here](https://github.com/reinforceio/tensorforce/blob/master/examples/quickstart.py#L39).

I assume this issue can be closed.
