### ISSUE TITLE
CI builds are breaking

### ISSUE THREAD

**Issue by mkempers** [reinforceio/tensorforce#333]
The CI builds are breaking. I believe a downgrade of the gym package will fix the issue. Also see, [cannot import name spaces #838](https://github.com/openai/gym/issues/838)!

I am not sure how to resolve this properly. Is , temporarily, setting a specific gym version in setup.py a good solution?
```pip install gym==0.9.5``` fixes the issue

**Comment by michaelschaarschmidt** [comment]
Hey, thanks for raising, yes we noticed that and will probably fix it in the memory branch, which will soon become the master

**Comment by michaelschaarschmidt** [comment]
Should be fixed via , thanks again https://github.com/reinforceio/tensorforce/commit/d444deef3444dcbbf9f5f0f131748fc6ff8b7894
