### ISSUE TITLE
Type error in ./tensorforce/environments/minimal_test.py

### ISSUE THREAD

**Issue by zeroinside** [reinforceio/tensorforce#339]
Hello.
I'm just begging in Your framework, but there's a issue introduced in version >0.3
In master branch, You can see this line:
https://github.com/reinforceio/tensorforce/blob/9d71ff3d424052cad818d73638da0b25964f5025/tensorforce/environments/minimal_test.py#L37

Which is incorrectly typed, in older version we can see:
        self.specification = list()
        for action in specification:
            if len(action) == 2 and action[0] in ('bool', 'int', 'float', 'bounded-float'):

Anyway, if its my mistake and I'm just using it in wrong (old) way, the comments aren't updated, so it's not easy to guess what author have in mind.

**Comment by AlexKuhnle** [comment]
This was indeed changed, on purpose, at some point -- note that this project is still in pre-alpha stage, and consequently in particular some of the internal names/signatures/etc change every now and then. And you're right, we're not always good at updating documentation. Note that the `MinimalTest` class is mainly used for internal unit test purposes, see [here](https://github.com/reinforceio/tensorforce/tree/master/tensorforce/tests), particularly `base_test` and `base_agent_test`.

**Comment by michaelschaarschmidt** [comment]
Fixed docs with https://github.com/reinforceio/tensorforce/commit/6c5a0a528bd4814ac5f983c96815f0c0fe35b097
