### ISSUE TITLE
PPO Agent with Multiple Action States

### ISSUE THREAD

**Issue by cinjon** [reinforceio/tensorforce#341]
Hi there, I'm trying to initialize a PPO Agent in Gym which has multiple discrete outputs, i.e. action_space = gym.spaces.Tuple(gym.spaces.Discrete(6), gym.spaces.Discrete(8)). How do I properly do this? I thought the following would work but I'm running into an error down the stack:

> ValueError: List argument 'values' to 'ConcatV2' Op with length 0 shorter than minimum length 2.

```
actions_spec = {str(num): {'type': int, 'num_actions': space.n}
                            for num, space in enumerate(env.action_space.spaces)}
return PPOAgent(states_spec=dict(type='float', shape=env.observation_space.shape),
                              actions_spec=actions_spec,
                              network_spec=[
                                  dict(type='dense', size=64),
                                  dict(type='dense', size=64)
                              ],
                              batch_size=128,
                              step_optimizer=dict(
                                   type='adam',
                                   learning_rate=1e-4
                              ))
```

**Comment by AlexKuhnle** [comment]
There is an OpenAIGym environment interface which defines how gym state/action spaces are mapped to TensorForce spaces [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/openai_gym.py#L112). Hope that helps, although what you do seems quite similar. Otherwise, it would be helpful to show more of the exception stack, to know where exactly the error is thrown.

**Comment by AlexKuhnle** [comment]
That's weird, can you print the actions_spec, just to make sure nothing is empty? Also, are you using the pip version of TensorForce, or the latest Github version?

**Comment by cinjon** [comment]
It prints out as:

`{'0': {'type': <class 'int'>, 'num_actions': 6}, '1': {'type': <class 'int'>, 'num_actions': 8}, '2': {'type': <class 'int'>, 'num_actions': 8}}`

I am using the pip version, which is tensorforce==0.3.5.1.

**Comment by AlexKuhnle** [comment]
Hmm, is it an environment I could also check, or can you reproduce the error on one of the public Gym environments? I don't really see why it doesn't work. On a different (but maybe related) note: We should fix a new version, since we had a major update recently.

**Comment by michaelschaarschmidt** [comment]
Hi,

I just reproduced this locally on the latest master and the test environment using your exact action specification and cannot see your error. Could you try this on master?
