### ISSUE TITLE
Adjusting Entropy Regularization

### ISSUE THREAD

**Issue by neighthan** [reinforceio/tensorforce#344]
Is it possible to adjust the `entropy_regularization` coefficient? I'm using a PPO agent, and I find that in my application I tend to quickly converge to a poor local optimum without a higher coefficient for this, but once I've explored a bit, I'd like to decrease the coefficient so I can more easily move to better trajectories (I seem to get stuck in too random of a policy). Currently I've tried doing something like:

```python
# Explore more
runner.run(episodes=500)
# Decrease coefficient
runner.agent.entropy_regularization = .001
# This ought to converge more now
runner.run(episodes=500)
```

but it doesn't seem to be converging. Does changing `entropy_regularization` here have no effect or is it being changed appropriately and the lack of better convergence after decreasing it is just something I'll have to figure out in my application?

**Comment by AlexKuhnle** [comment]
Hey @neighthan,

Your suspicion is correct, changing the value doesn't do anything, since the initial value gets built into the TensorFlow graph on model construction. There is currently no good way of achieving this, however, there's a feature I have in mind which would make this possible, and hope to get around implementing it soon.

**Comment by mysl** [comment]
@AlexKuhnle hi,  where are we for this currently? Thanks!

**Comment by neighthan** [comment]
There may well be better solutions to this, but one that I'd expect to be fairly straightforward would be to make the entropy a `tf.placeholder_with_default`; the default can be whatever the user passes in, as usual, and then for people who don't want to change the entropy, nothing will be different. If one does want to change it, you'll have to feed a value for that placeholder every time, but at least it would be doable. Is there an easier way to change the value so that you can just change it once and not need to feed it again after that (unless changing it again)?

**Comment by neighthan** [comment]
@AlexKuhnle can you point me at where in your code base the specifications for exploration are handled so we can see that as an example? I don't know if I'll have time for this, but if it becomes something that I need again, I'll look into it (otherwise, it'd be useful for anybody else looking at this issue too)

**Comment by AlexKuhnle** [comment]
The exploration module is called [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/model.py#L860) and the available exploration modules are [here](https://github.com/reinforceio/tensorforce/tree/master/tensorforce/core/explorations). `constant` in that case would be equivalent to a fixed given value, while other modes like `epsilon_decay` would be timestep-variable values, for instance. Of course one might need to consider a few more things before generalizing it to other config values, but that's how I would start.

**Comment by AlexKuhnle** [comment]
I assume this is not active anymore. If you're still interested in contributing such a feature, let me know (best get in touch via Gitter).
