### ISSUE TITLE
result logging and policy saving

### ISSUE THREAD

**Issue by xli4217** [reinforceio/tensorforce#35]
Hi, maybe I'm missing something but where do you save the various training metrics (returns, entropy, etc) and is there a mechanism to save the trained model or do we have to implement that. Thanks!

**Comment by michaelschaarschmidt** [comment]
Hi,

if you look at the example scripts, you can log high level performance metrics in the runner using the episode_finished callback. Wrt internal metrics such as returns, entropy you would have to currently export that. There is also a parameter for passing a summary writer location in the config.

We are very aware of this though (also https://github.com/reinforceio/tensorforce/issues/32), so we will overhaul the logging in one of the next dev sessions.

**Comment by xli4217** [comment]
Ok, thanks.
