### ISSUE TITLE
Save and restore model components individually

### ISSUE THREAD

**Issue by janislavjankov** [reinforceio/tensorforce#363]
In certain scenarios it is useful to be able to pre-load the network and distribution parameters, or store them separately after training so they can be used in different models. Currently, as the Model builds the graph, creates the save and restore operations (through Saver) and then finalizes the graph, implementing the separate save/restore, although achievable, cannot be done in a robust and future proof way.

My proposal is to change the Model to provide hooks so that the components (such as Network, Distribution) can declare that they'll manage their parameters and initialize the necessary operations. The model will also invoke save/restore on such components within its own save and restore methods.

More specifically the proposal is to
1. Add a mixin SaveableComponent, which the components can implement, like this:

```
class SaveableComponent(object):
    """
    A component that can save and restore it's own state.
    """

    def init_save(self):
        """
        Invoked when the saver operations have to be initialized.
        """
        # init tf.Saver here

    def get_managed_variables(self):
        """
        Returns the list of all the variables this component is responsible to save and restore.

        Returns:
            The list of managed variables.
        """
        return list()

    def save(self, sess, directory, timestep=None):
        """
        Saves this component's managed variables.

        Args:
            sess: The session for which to save the managed variables.
            directory: The location where to write the data.
            timestep: Optional, the timestep to append to the file name.

        Returns:
            Checkpoint path where the model was saved.
        """
        # invoke saver.save()

    def restore(self, sess, directory, file=None):
        """
        Restores the values of the managed variables from disk location.

        Args:
            sess: The session for which to save the managed variables.
            directory: Optional checkpoint directory.
            file: Optional checkpoint file, or path if directory not given.
        """
        # invoke saver.restore()

```

2. Add a method to the Model's interface ```get_components()``` which will allow the specific implementations to list all of their parameterized components such as Network and Distribution.
3. Within Model's setup, before creating the saver, the model will inspect the components and if they implement the interface ```SaveableComponent``` it will invoke ```init_save()``` on them and will keep track of all their managed variables so they are excluded from the model's own Saver.
4. Upon save/restore the model will invoke for the components that implement ```SaveableComponent ``` the save/restore methods.

**Comment by michaelschaarschmidt** [comment]
Hi,
this sounds like a good idea in general and I agree that it would be nice to load separate components, typically the main network layers I would assume. 

How would this interfer/work with distributed mode where each worker could load separate values?

**Comment by janislavjankov** [comment]
Hi @michaelschaarschmidt,
I don't have much experience in running in distributed mode. Is there a test or minimal setup I can use to give it a try? In this proposal as the save/restore of the model invokes the save/restore of the components and as we can pass the same set of parameters it should give enough control of the component to load and save the state appropriately. Thoughts?

**Comment by michaelschaarschmidt** [comment]
There is an async example in the examples folder using distributed mode. However, the distributed mode will soon be revamped to make it more explicit what is going on, so I suppose for now it's not that important. Feel free to get started on a PR for an example integration for e.g. networks..

**Comment by michaelschaarschmidt** [comment]
Merged PR
