### ISSUE TITLE
Multiple agents with shared model in same environment

### ISSUE THREAD

**Issue by ingkanit** [reinforceio/tensorforce#371]
First of all, thanks a lot for your amazing work here!

I am trying to use Tensorforce to implement a multi-agent environment where agents interact with each other. Agents have their own observations and rewards but share the model parameters for their policies. To implement this, I created a new multi-runner class that keeps track of the interactions of multiple agents with the same environment.

The problem I have is that if several agents share the same model, and this model is called consecutively using observe() from different agents it seems to mess up the experience the model receives. Is there an obvious way to implement this using Tensorforce or is it beyond its scope for now?

**Comment by michaelschaarschmidt** [comment]
Hi,
this is something multiple people are experiment atm, I recommend joining the gitter (see readme). In general there is a counter for act() and observe(), and if an act is NOT followed by an observe you have to set the independent flag to true. This might however not address your distributed issues, and the distributed mode is being revamped.

**Comment by ingkanit** [comment]
Ok, thanks, I'll keep my eyes open!

**Comment by andreaspasternak** [comment]
I solved it this way: 
After every episode, I select another agent which learns. The other agents just act according to an action provided by:
`action = self.agent.act((self.current_response.observations[id]), independent=True, deterministic=True)`.

This is of course highly sample inefficient, but it works for me for now. But I want to extend it, but I am not enough familiar with the tensorforce code.

**Comment by AlexKuhnle** [comment]
Since I don't expect this to be fundamentally improved soon, the best way to achieve this is to use async mode with a shared environment, although I realize that this is not straightforward. If you have other ideas and want to get involved, I'm happy to try and be helpful.

**Comment by KiloNovemberDelta** [comment]
Hello everyone,
I know it is a closed issue, but I'm interested by this subject too. 
Is there any news in how to implement this multi-agent case? 
Thanks !

**Comment by AlexKuhnle** [comment]
Hi @KiloNovemberDelta, as it happens, I'm looking into that right now. :-)  However, this issue is very old, mind opening a new one, and we can discuss there?
