### ISSUE TITLE
Agent setting for only taking action without model update

### ISSUE THREAD

**Issue by mysl** [reinforceio/tensorforce#372]
Hi there,
I am wondering if there is any setting of the agent I can set so that after some iterations of training, then I can use the same agent to run some evaluation iterations to only take actions without model update?  My goal is to run  (training1, evaluation1), (training2, evaluation2), .... (trainingN, evaluationN) with the agent without recreating it in the middle.  Is that doable?
I tried in the evaluation phase,  only calling act(), skip calling observe(), but there will be exceptions raised.
Any comment is appreciated!

**Comment by michaelschaarschmidt** [comment]
If you only want to call act in the evaluation, set independent=True in act()

**Comment by mysl** [comment]
@michaelschaarschmidt ,  it works,  thanks a lot!
