### ISSUE TITLE
Can't run quickstart example (OpenAI gym) when installing from pip

### ISSUE THREAD

**Issue by mx781** [reinforceio/tensorforce#373]
When running the quickstart given in the README or the one in `examples/openai_gym.py` itself, I am getting some errors.

Command I am running and output:
```
$ python3 examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "examples/openai_gym.py", line 140, in <module>
    main()
  File "examples/openai_gym.py", line 89, in main
    network=network
  File "/usr/local/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 239, in from_spec
    kwargs=kwargs
  File "/usr/local/lib/python3.6/site-packages/tensorforce/util.py", line 173, in get_object
    return obj(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'states'
```

The one in the file itself (which specifies a different config file and -n & -m flags) or the async example also does not work.

**This seems to happen with any TensorForce/Gym version combination installed via pip, but does not occur when installing from source (`git clone ... && pip install -e .`).**

I am running:
- Python 3.6.4 on macOS 10.13.3
- Tensorforce 0.3.5.1 (Installed as tensorforce[tf])
- Tensorflow 1.6.0

Not sure if examples are intended to be run only when installing from source, but just pointing your attention to this in case someone else gets stumped by the quickstart command.

**Comment by michaelschaarschmidt** [comment]
yep the pip version needs updating, will do soon, should work from master

**Comment by michaelschaarschmidt** [comment]
new pip version up, we were holding out bcause prioritized replay in pure tensorflow is complicated, but I guess that will be 0.4.1 then. Closing now, reopen if still doesnt work
