### ISSUE TITLE
How to set random seed

### ISSUE THREAD

**Issue by mysl** [reinforceio/tensorforce#375]
Hi,  a quick question.  Is there a way to set random seed in tensorforce?  Thanks!

**Comment by michaelschaarschmidt** [comment]
Hi,
I think you can set a seed in tensorflow somewhere
https://www.tensorflow.org/api_docs/python/tf/set_random_seed
This however depends on the scope, so you might have to place that somewhere in the model..

**Comment by mysl** [comment]
ok, got it thanks

**Comment by ecorreig** [comment]
Hi, how did you do it, @mysl? I can get the vpg agent to give the same results twice. 

Thanks!

**Comment by AlexKuhnle** [comment]
The newer branch versions should support this, see [here](https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/agents/agent.py#L82). Alternatively, it should be possible to just call these three lines before instantiating an agent.

**Comment by ecorreig** [comment]
Yeah, I already did this and also call the lines but with no luck...

**Comment by ecorreig** [comment]
Oh, by the way, there is a small bug in here I think; now random.seed has the parameter "a", not "n", so, at line it should be
`random.seed(a=seed)`

**Comment by AlexKuhnle** [comment]
Can you post the lines how you call Tensorforce after setting seeds? I assume your environment does not introduce any randomness?

**Comment by ecorreig** [comment]
It's a little involved and the code is protected... :-( 
The environment introduces randomness but it should be under control with more random seeds. 

I'll try to get a minimal example and get back to you; thanks for the help!

**Comment by AlexKuhnle** [comment]
Yes, that would be great, thanks.
