### ISSUE TITLE
unexpected keyword argument

### ISSUE THREAD

**Issue by tennenboke** [reinforceio/tensorforce#379]
Run an example:threaded_ale.py, throw an exception
tensorforce 0.4.0, ubuntu14.04, python2.7

~/PycharmProjects/untitled/tensorforce/examples$ python threaded_ale.py /home/zlj/PycharmProjects/untitled/atari-py/atari_py/atari_roms/breakout.bin -a configs/dqn_visual.json -n configs/cnn_dqn2013_network.json -fs 4 -ea -w 4
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  /home/zlj/PycharmProjects/untitled/atari-py/atari_py/atari_roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Screen Display Active. [Manual Control Mode] 'm' [Slowdown] 'a' [Speedup] 's' [VolumeDown] '[' [VolumeUp] ']'.

WARNING: Possibly unsupported ROM: mismatched MD5.
Cartridge_MD5: f34f08e5eb96e500e851a80be3277a56
Cartridge_name: Breakout - Breakaway IV (1978) (Atari)

Running ROM file...
Random seed is 3116
A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  /home/zlj/PycharmProjects/untitled/atari-py/atari_py/atari_roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Screen Display Active. [Manual Control Mode] 'm' [Slowdown] 'a' [Speedup] 's' [VolumeDown] '[' [VolumeUp] ']'.

WARNING: Possibly unsupported ROM: mismatched MD5.
Cartridge_MD5: f34f08e5eb96e500e851a80be3277a56
Cartridge_name: Breakout - Breakaway IV (1978) (Atari)

Running ROM file...
Random seed is 5523
A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  /home/zlj/PycharmProjects/untitled/atari-py/atari_py/atari_roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Screen Display Active. [Manual Control Mode] 'm' [Slowdown] 'a' [Speedup] 's' [VolumeDown] '[' [VolumeUp] ']'.

WARNING: Possibly unsupported ROM: mismatched MD5.
Cartridge_MD5: f34f08e5eb96e500e851a80be3277a56
Cartridge_name: Breakout - Breakaway IV (1978) (Atari)

Running ROM file...
Random seed is 9699
A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Warning: couldn't load settings file: ./ale.cfg
Game console created:
  ROM file:  /home/zlj/PycharmProjects/untitled/atari-py/atari_py/atari_roms/breakout.bin
  Cart Name: Breakout - Breakaway IV (1978) (Atari)
  Cart MD5:  f34f08e5eb96e500e851a80be3277a56
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Screen Display Active. [Manual Control Mode] 'm' [Slowdown] 'a' [Speedup] 's' [VolumeDown] '[' [VolumeUp] ']'.

WARNING: Possibly unsupported ROM: mismatched MD5.
Cartridge_MD5: f34f08e5eb96e500e851a80be3277a56
Cartridge_name: Breakout - Breakaway IV (1978) (Atari)

Running ROM file...
Random seed is 9033
{u'update_mode': {u'frequency': 4, u'unit': u'timesteps', u'batch_size': 64}, u'summarizer': {u'directory': None, u'seconds': 120, u'labels': []}, u'optimizer': {u'learning_rate': 0.001, u'type': u'adam'}, u'states_preprocessing': [{u'width': 84, u'type': u'image_resize', u'height': 84}, {u'type': u'grayscale'}, {u'scale': 255, u'type': u'divide'}], u'saver': {u'directory': None, u'seconds': 600}, u'discount': 0.97, u'memory': {u'type': u'replay', u'include_next_states': True, u'capacity': 10000}, u'actions_exploration': {u'type': u'epsilon_decay', u'final_epsilon': 0.1, u'initial_epsilon': 1.0, u'timesteps': 100000}, u'execution': {u'distributed_spec': None, u'type': u'single', u'session_config': None}, u'type': u'dqn_agent'}
Traceback (most recent call last):
  File "threaded_ale.py", line 192, in <module>
    main()
  File "threaded_ale.py", line 119, in main
    network_spec=network_spec
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/agent.py", line 291, in from_spec
    kwargs=kwargs
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 159, in get_object
    return obj(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'network_spec'

**Comment by michaelschaarschmidt** [comment]
API update error, fixed
