### ISSUE TITLE
TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

### ISSUE THREAD

**Issue by johnmoberg** [reinforceio/tensorforce#381]
I'm trying to run a DQN with the configuration provided in the examples as follows:
> python3 examples/openai_gym.py CartPole-v0 -a examples/configs/dqn.json -n examples/configs/mlp2_network.json

This gives me the error
> File "/home/tensorforce/tensorforce/core/memories/replay.py", line 83, in resample_fn
>     maximum_iterations=10
> TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

Tracking it down to replay.py, I find the call
`sampled_indices = tf.while_loop(cond=cond, body=sampling_body, loop_vars=[indices], maximum_iterations=10)`
and if I remove the maximum_iterations argument, it works just fine. Should this argument be here?

**Comment by michaelschaarschmidt** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/control_flow_ops.py#L2987

You are likely using an old tensorflow version.
