### ISSUE TITLE
action space output to a single number from agent - Help!

### ISSUE THREAD

**Issue by suvam-bag** [reinforceio/tensorforce#394]
Hi,

I noticed that "self.agent.act" gives a single discrete number, whereas the output from a saved/restored is a discrete action space. By output, I am taking the output from the "ppo/actions-and-internals/categorical/parameterize/Softmax" layer after freezing the graph. I looked into the source code, but couldn't exactly figure out, how the "agent" gives a discrete number. 
Am I taking the wrong output?

Any help would be hugely appreciated. Thanks!

**Comment by andreaspasternak** [comment]
I am also using the PPO agent and saving, restoring works as expected.

Can you provide a minimal code example that shows the problem you have?

**Comment by suvam-bag** [comment]
Hi @andreaspasternak ,

I am unable to provide my code right now but this is what I ended up doing.  I took the index of the highest output of the Softmax layer as my output. I will try to provide a minimal code example in the future.

**Comment by AlexKuhnle** [comment]
Is this still a problem in the most recent version? If so, can you provide a minimal example?

**Comment by AlexKuhnle** [comment]
Assuming this is not an issue anymore.
