### ISSUE TITLE
summarizer error: loss-without-regularization as input to 'Merge/MergeSummary'

### ISSUE THREAD

**Issue by mpecenin** [reinforceio/tensorforce#396]
I'm trying to use summarizer as showed in [summary_spec.md](https://github.com/reinforceio/tensorforce/blob/master/docs/summary_spec.md) example, configuring labels in the agent example config file (ppo.json), like this:
```
    "summarizer": {
        "directory": "./output",
        "labels": [
            "losses"
        ],
        "seconds": 120
    },
```

And running:
`python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json`

But no success, it shows the following error. Also have the same error changing label to 'total-loss'.

Traceback (most recent call last):
  File "examples/openai_gym.py", line 158, in <module>
    main()
  File "examples/openai_gym.py", line 105, in main
    network=network,
  File "python2.7/site-packages/tensorforce/agents/agent.py", line 241, in from_spec
    kwargs=kwargs
  File "python2.7/site-packages/tensorforce/util.py", line 175, in get_object
    return obj(*args, **kwargs)
  File "python2.7/site-packages/tensorforce/agents/ppo_agent.py", line 151, in __init__
    entropy_regularization=entropy_regularization
  File "python2.7/site-packages/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "python2.7/site-packages/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "python2.7/site-packages/tensorforce/agents/ppo_agent.py", line 179, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "python2.7/site-packages/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "python2.7/site-packages/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "python2.7/site-packages/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "python2.7/site-packages/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "python2.7/site-packages/tensorforce/models/model.py", line 220, in __init__
    self.setup()
  File "python2.7/site-packages/tensorforce/models/model.py", line 298, in setup
    summary_op = tf.summary.merge(inputs=summaries)
  File "python2.7/site-packages/tensorflow/python/summary/summary.py", line 284, in merge
    val = _gen_logging_ops._merge_summary(inputs=inputs, name=name)
  File "python2.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 314, in _merge_summary
    "MergeSummary", inputs=inputs, name=name)
  File "python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "python2.7/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "python2.7/site-packages/tensorflow/python/framework/ops.py", line 1672, in __init__
    control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
  File "python2.7/site-packages/tensorflow/python/ops/control_flow_util.py", line 200, in CheckInputFromValidContext
    raise ValueError(error_msg + " See info log for more details.")

ValueError: Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-without-regularization' as input to 'Merge/MergeSummary' because 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-without-regularization' is in a while loop.

**Comment by zishanahmed08** [comment]
I faced the same issue.Did u find a resolution to this

**Comment by mpecenin** [comment]
no, not yet

**Comment by nisace** [comment]
According to [this tensorflow issue](https://github.com/tensorflow/tensorflow/issues/10059), it seems that `tf.contrib.summary` should be used instead of `tf.summary`.

But there are many API changes. What are your thoughts on this? I haven't look at it a lot yet and I don't know how heavy it would be to turn to `tf.contrib.summary`.

**Comment by AlexKuhnle** [comment]
Yes, `tf.contrib.summary` seems the way to go. I attempted to change things accordingly, but some problem remained, which seemed like it might be a bug in TensorFlow -- different from the problems we encounter with `tf.summary`, where the mechanisms seem to just not generalize to more complex conditional/while control structures.

**Comment by nisace** [comment]
Does it mean there is no way to solve the issue for now? What other problems are you referring to?

**Comment by AlexKuhnle** [comment]
I'm not sure, `tf.contrib.summary` is definitely the right way to go, but I got stuck back then when I tried it. Might have been a problem on my side, maybe it is/was a bug in TensorFlow. I can potentially check at some point whether I can replicate what exception I got, and/or what changes I made, but no promises.

**Comment by b-kartal** [comment]
Still getting the same error.

ValueError: Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-without-regularization' as input to 'Merge/MergeSummary' because 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-without-regularization' is in a while loop. See info log for more details.

**Comment by gerardsimons** [comment]
I am also having this issue with TensorFlow 1.8.0 and TensorForce 0.4.2. 

Changing the faulty line (301 in model.py) from

`summary_op = tf.summary.merge(inputs=summaries)`

to 

`summary_op = tf.contrib.summary.merge(inputs=summaries)`

**Comment by Arjuna197** [comment]
It isn't the merge that needs to be contrib, according to above, its the summary generation itself

**Comment by gerardsimons** [comment]
Right, that makes sense, thanks @Arjuna197 . 

However when I replace all of those, I get the following issue:

TypeError: Tensors in list passed to 'inputs' of 'MergeSummary' Op have types [<NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>] that do not match expected type string.

This is when I add "losses" to the summarized. Any ideas?

**Comment by AlexKuhnle** [comment]
@all, the summarizers should work again with the latest commit, and the code now uses the new `tf.contrib.summary` framework. It's now relatively easy to add own summarizers in the code, just decide for a tag to be added to `summary_labels` and add the corresponding `tf.contrib.summary` command, as is done, for instance, [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/memory_model.py#L423):
```
if 'losses' in self.summary_labels or 'total-loss' in self.summary_labels:
    tf.contrib.summary.scalar(name='total-loss', tensor=loss)
```
I haven't thoroughly checked existing labels, but preliminary tests worked well. Let me know if you encounter any problems.

**Comment by WoojuLee24** [comment]
Thank you AlexKuhnle
I changed my code to 
if 'losses' in self.summary_labels or 'total-loss' in self.summary_labels:
    tf.contrib.summary.scalar(name='total-loss', tensor=loss)
But there is an error 
ValueError: Cannot use 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-without-regularization' as input to 'Merge/MergeSummary' because 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-without-regularization' is in a while loop. See info log for more details.
