### ISSUE TITLE
Episode reward summary in tensorboard for PPO agent

### ISSUE THREAD

**Issue by zishanahmed08** [reinforceio/tensorforce#397]
Firstly,Thanks for this great Library and good luck with your PhD.

Secondly,This is more of a question than an issue.
I need to get the summary(logging) of Episode reward for the PPO agent.
Looking at the documentation, it indicates that feature is not yet available.

There were 2 PRs related to this
1)https://github.com/reinforceio/tensorforce/pull/305 which was closed
2)https://github.com/reinforceio/tensorforce/pull/99 which was merged

Could you please confirm it its possible to get the episode reward on the tensorboard for PPO agent?

**Comment by yellowbee686** [comment]
#305 is not finished and #99 is the older version, so now there is no episode_reward summary in tensorforce

**Comment by zishanahmed08** [comment]
Cool! Thanks for the info.
