### ISSUE TITLE
OpenAIGym Environment does not support Dict/nested spaces

### ISSUE THREAD

**Issue by dwilson1988** [reinforceio/tensorforce#405]
I built a gym environment for a problem I'm working on. My action space looks like:
```python
import gym
from gym import spaces

class MultipleMoverGridWorld(gym.Env):
    ...
    def __init__(self):
        self.action_space = spaces.Dict({
        "mover{}".format(i): spaces.Discrete(5) \
                for i in range(self.n_movers)
        })
```
with each mover in my grid world having 5 possible actions (up/down/left/right/null). My environment allows multiple movers to change position each time step. I get the following error when trying to get the tensorforce actions:
```
---------------------------------------------------------------------------
TensorForceError                          Traceback (most recent call last)
<ipython-input-515-20ed75416bda> in <module>()
----> 1 OpenAIGym.action_from_space(space=env.action_space)

~\AppData\Local\ESRI\conda\envs\cpd\lib\site-packages\tensorforce\contrib\openai_gym.py in action_from_space(space)
    150             return actions
    151         else:
--> 152             raise TensorForceError('Unknown Gym space.')

TensorForceError: Unknown Gym space.
```

Near as I can tell, I should be able to implement the functionality in tensorforce as:
```
actions = {
    "mover{}".format(i): dict(type='int', num_actions=5) \
            for i in range(self.n_movers)
}
```

I can definitely work on a PR for this if there's interest, but definitely want to check if there's a workaround first. I have my environment implemented as an OpenAI gym and would prefer not to reimplement as a tensorforce environment if I have the option. :)

EDIT: I should also add that this is only a minimal example of this: my action space will be a little more complex in the future.

**Comment by AlexKuhnle** [comment]
Hey, this is just due to a missing conversion of `gym.spaces.Dict` (maybe a more recent feature, because I think we implemented all existing space types back then). Hence I would suggest modifying/extending the `tensorforce.contrib.openai_gym.py` file accordingly in a PR ([here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/openai_gym.py#L104) and [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/openai_gym.py#L151)), instead of implementing your own TensorForce environment. The conversion should be straightforward, since we are using only dicts.

**Comment by AlexKuhnle** [comment]
Yes, sure, that would be welcome! Similar to how the branch for `gym.spaces.Tuple` does already flatten arbitrary nesting, I would expect that concatenating the dict key strings with '-' or so could work. We never actually experimented with nested spaces, I think, so you might also need some 'unpacking' in the `execute` method, which doesn't at all exist yet.

**Comment by dwilson1988** [comment]
Ah, I see what you mean! I hadn't noticed the recursion in the case for `gym.spaces.Tuple`. I'll implement the same functionality for `gym.spaces.Dict` and think about where the unpacking needs to occur.
