### ISSUE TITLE
DQN not improving

### ISSUE THREAD

**Issue by watterm** [reinforceio/tensorforce#407]
Hey,

I updated to the current tensorforce version and my experiments with DQN are no longer working. I also tried the example configuration for the cartpole, but the rewards start from 13 and go down to ~9. Presumably starting higher because of exploration and then indicating that either the model is not being trained or something else goes wrong. The problem is consistent for me using the benchmarking repository:

> python3 scripts/benchmark_gym.py --output benchmarks/cartpole configs/dqn_cartpole.json CartPole-v1

![output](https://user-images.githubusercontent.com/10044898/39620203-a5863bb6-4f8a-11e8-8eb9-78fa8c07dad1.png)

Can you confirm this behavior or is it on my end?

Libraries:
Tensorflow: 1.6
Tensorforce: current master
Gym: 0.1.1

**Comment by michaelschaarschmidt** [comment]
So my dqn based experiments seem to work, but I had to change configurations, not certain what the issue is, because there is no obvious bug I am aware of

**Comment by watterm** [comment]
Okay, so traced it down to the replay memory. I have a somewhat special case, where each episode only has 1 transition, so in `Replay.tf_retrieve_timesteps`, they are all marked as terminal and an empty list gets returned. If I simply return the indices without the resampling, my experiments work. Why are terminal transitions being excluded from the sampling here?

Disabling the `include_next_states` flag in the memory config seems not to be possible, because even if I remove the assertion in the dqn_agent, there seem to be more things depending on it.

Changing the retrieve_timesteps function did not improve things for running the benchmarks, though. It might be possible that this is only due to bad settings. What did you change for your experiments and have you tried it with the current default settings on the CartPole-v1 environment? DQFD shows the same behavior for me there.

**Comment by michaelschaarschmidt** [comment]
Ah yes, so this was due to: https://github.com/reinforceio/tensorforce/issues/353, the sampling loop was a fix for that.

Next states are normally definitely required to make dqn work. I have not tried it on cartpole but I would not be surprised if the settings dont work or not every time, so I would not necessarily trust that. I can just tell that I in the experiments I have been running with dqfd the online reward curve generally seems to look as expected.

**Comment by watterm** [comment]
Hmm okay, so in my case I have transitions (s, a, s') that are all marked as terminal as s' is a terminal state. The resampling can't fix that, because I have no other transitions. A solution on my end would be to introduce dummy transitions (s', a', s'') as terminal. But I'm not sure I understand why the exclusion of terminal transitions is necessary in the first place?

**Comment by michaelschaarschmidt** [comment]
Because otherwise you would think that the first state of a new episode is the next state after a terminal state

**Comment by michaelschaarschmidt** [comment]
Ok, good!
