### ISSUE TITLE
 ImportError: cannot import name 'Configuration'

### ISSUE THREAD

**Issue by Bellman281** [reinforceio/tensorforce#411]
Just installed the latest version and got this error:

from tensorforce import Configuration
Traceback (most recent call last):

  File "<ipython-input-2-e85ef226f1e8>", line 1, in <module>
    from tensorforce import Configuration

ImportError: cannot import name 'Configuration'

**Comment by michaelschaarschmidt** [comment]
The Configuration object has been deprecated multiple version ago, please update -
