### ISSUE TITLE
How to set different actions for different states 

### ISSUE THREAD

**Issue by tianv** [reinforceio/tensorforce#413]
First, thanks for your great work! 
Let me use the following example to explain my question.

When state=1, actions = [a1, a2, a3]
When state=2, actions = [a1, a2]
for state =2 , a3 is 100% not happened. So don't need to add a3 to actions to train. 
So, how can I set different actions for different states ?

**Comment by michaelschaarschmidt** [comment]
Hi,
state dependent actions are not supported, you have to handle this is in your application
