### ISSUE TITLE
agent.restore_model Error

### ISSUE THREAD

**Issue by bching28** [reinforceio/tensorforce#417]
I am not sure why I am getting an error for this.  I save the model using:
`agent.save_model(directory="./saved/", append_timestep=False)`

I load the model using:
`agent.restore_model(directory="./saved/", file="checkpoint")`

However I am still getting this error:
```
DataLossError (see above for traceback): Unable to open table file ./saved/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

I have taken a look at [https://github.com/reinforceio/tensorforce/issues/229](url) but I still can't figure out what is wrong.

**Comment by kevinanschau** [comment]
Try
`agent.restore_model(directory="./saved/")`

If you do not specify the "file" keyword in agent.restore_model(), then it should load the most recent checkpoint in the given directory.

Also, if I am not mistaken, when you use 
`agent.save_model(directory="./saved/", append_timestep=False)`,
the filename of the checkpoint will be empty, i.e. `.meta`.

**Comment by AlexKuhnle** [comment]
Did the latest comment help? I think you have to specify the entire filename if you want to select a specific checkpoint. Otherwise best to leave it empty...

**Comment by bching28** [comment]
Yes, sorry for the delayed response.  For my code, I used `agent.restore_model(args.load)` where `args.load` is a parameter when the user runs the program.  For example, the user inputs `./saved/`, and the model should restore properly from this directory in this case.

**Comment by AlexKuhnle** [comment]
Does this mean it works now (trying the things suggested above)?

**Comment by bching28** [comment]
Yes, it works. I will close the issue.
