### ISSUE TITLE
weights are not being updated

### ISSUE THREAD

**Issue by oron99** [reinforceio/tensorforce#420]
Im am using PPOagent with the suggested parameters in the Examples/configs/ppo
I changed "bactch_size" in "update mode" to 1 and "frequency" to 1
I did not used the runner script. I wrote my self the commands
agent.act(states=enviroment.states)
agent.observe(reward=enviroment.reward,terminal=enviroment.terminal)

I monitored the network weights by the line
print(sess.run(tf.global_variables()))

The weights are not changing with time, 
Why is the network not being trained?
Thank for your help

**Comment by oron99** [comment]
yes is solved the problem. Thank you
But now when i try to load previous checkpoint  i get the next error:
InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape +params.shape[1:], got updates.shape [33, 17], indices.shapes [17], params.shape [5000,17]

This happens when act.observe is perform with terminal = True
If i run the script without loading previous checkpoint it runs without errors
I tried to load previous checkpoint with actor.restore_model(modelDir)
How can i load previous checkpoint?
Thank for your help

**Comment by AlexKuhnle** [comment]
Did [this recent PR](https://github.com/reinforceio/tensorforce/pull/422) fix the problem?

**Comment by oron99** [comment]
Yes
Thank you
