### ISSUE TITLE
global_step issues when using the summarizer

### ISSUE THREAD

**Issue by dholzmueller** [reinforceio/tensorforce#429]
Hello,

I tried to run the examples/openai_gym_async.py script with the standard Pong-ram-v0 command but using a changed vpg.json to output summaries. These are the changed lines:
```
    "saver": {
        "directory": "vpg_summary",
        "seconds": 600
    },
    "summarizer": {
        "directory": "vpg_summary",
        "labels": ["inputs", "gradients"], 
        "seconds": 20
    }
```

I get the following error message in every worker:
`ERROR:tensorflow:Multiple tensors in global_step collection.`

These errors are followed by 
`RuntimeError: Global step should be created to use CheckpointSaverHook.`
in worker 0 and 
`RuntimeError: Global step should be created to use SummarySaverHook.`
in workers 1 and 2. They are caused by not being able to get a global_step variable.

Does anyone know an easy fix for this issue? I use the current master branch, tensorflow 1.6.0 and gym[atari] on Ubuntu 16.04. I also tried different summarizer labels and I also get the error if I only use one worker.

**Comment by michaelschaarschmidt** [comment]
Please refer to https://github.com/reinforceio/tensorforce/issues/415
