### ISSUE TITLE
Load and test a learned policy

### ISSUE THREAD

**Issue by xli4217** [reinforceio/tensorforce#43]
Hi, I was wondering if there's currently a straightforward way to load a saved policy and run that policy with an environment without training updates, or do I have to write my own runner for this purpose. Thanks.

**Comment by michaelschaarschmidt** [comment]
Hi,

the runner is just an example for how to use the library, so yes, you would have to build that yourself, but that should just be taking the runner, calling load on your model somewhere, and commenting out the training/observe.

**Comment by xli4217** [comment]
Sounds good. Thanks.
