### ISSUE TITLE
[openai_gym.py] test code in master?

### ISSUE THREAD

**Issue by tgianko** [reinforceio/tensorforce#430]
Hi all,

Is this [openai_gym.py#L92](https://github.com/reinforceio/tensorforce/blob/master/examples/openai_gym.py#L92) the result of an accidental commit?

Best,
Giancarlo

**Comment by michaelschaarschmidt** [comment]
Yes, should have seen that in the PR, do you have time to create a PR to remove it?

**Comment by tgianko** [comment]
Yep, done. Waiting for approval

**Comment by michaelschaarschmidt** [comment]
Thanks!
