### ISSUE TITLE
A question about internal_lstm

### ISSUE THREAD

**Issue by lynic** [reinforceio/tensorforce#434]
The shape of state after tf.stack is (self.size, 2), https://github.com/reinforceio/tensorforce/blob/0.4.2/tensorforce/core/networks/layer.py#L1112

But at https://github.com/reinforceio/tensorforce/blob/0.4.2/tensorforce/core/networks/layer.py#L1102
it indicate that the input state shape is (batch, 2, self.size)

I'm wondering if there is any reshape process somewhere else in the code?

**Comment by AlexKuhnle** [comment]
In your first code reference, before the line, state.c and state.h are of size `(batch, self.size)` each. Stacking the two tensors for `axis=1` results in `(batch, 2, self.size)`, so everything should be fine.
