### ISSUE TITLE
Use output of a custom network as action

### ISSUE THREAD

**Issue by shivangag** [reinforceio/tensorforce#436]
I have created a custom network with an encoder-decoder architecture of 3D convolutions. My action space is a 32x32x32 volume with softmax activation.
How can I use this to infer my action, which is an ordered list [x, y, z], without any extra dense layer which is added by action_spec?

**Comment by daggertye** [comment]
It depends on the output of the decoder. 

If the output of the decoder is a 1x32x32x32 tensor, for example, then we are done relatively easily. Otherwise, if it has different dimensions, then dense layers are probably best for reshaping it to our desired output.

**Comment by shivangag** [comment]
Output of the decoder is a 1x32x32x32 tensor. I'm adding doing a softmax over the 32x32x32 volume and returning it as an action, the shape still being 1x32x32x32. But tensorforce throws the following error:

`    'Invalid input rank for linear layer: {}, must be 2.'.format(util.rank(x))
tensorforce.exception.TensorForceError: Invalid input rank for linear layer: 4,
must be 2.`

It looks like that tensorforce expects a rank 2 tensor as output from a custom network, which it then uses with a dense layer to output actions with desired shapes.

**Comment by AlexKuhnle** [comment]
Dense layers by definition require a rank 2 tensor. However, if you just specify the action space according to your needs, i.e. `(32, 32, 32)`, this should work (although it's a massive space, so no idea whether it works well).

**Comment by shivangag** [comment]
Yes. Thank you.
