### ISSUE TITLE
Using a custom environment with different discrete modes (progressive difficulty)

### ISSUE THREAD

**Issue by vderm** [reinforceio/tensorforce#437]
First of all, beautiful work, supremely useful!

Question: I've made a custom OpenAI environment and it runs well. My plan is to make the environment progressively more difficult until it's more-or-less realistic.

To keep it simple, from one discrete mode to the next, what changes are the penalty weights. Ex:
+ Mode 0: super easy, penalty = 0.1
+ Mode 1: easy, penalty = 1
+ Mode 2: normal, penalty = 10, etc.

What would be a simple way to do it? I'd rather not duplicate the environment for such a minor difference.

Thank you,
Vasken

**Comment by vderm** [comment]
I decided to have this as part of the environment by keeping track of the rewards over time and as they stagnate, slowly change the mode to a more difficult case.

Thank you nevertheless!
Vasken

**Comment by AlexKuhnle** [comment]
This seems like the right way to do what you want to achieve, as it can't really be handled from the agent-side. Hope the solution works!
