### ISSUE TITLE
type-conflict int (=state) vs. float(weights)

### ISSUE THREAD

**Issue by kiliangrundl** [reinforceio/tensorforce#441]
Hello!

I'm just getting into the system, so I don't know if I report an actual error, or if I'm just doing something wrong. In that case I'm sorry, but I'd still be grateful, if you could help me out anyway.

I'm trying to setup my own environment, which should have (for the start) a one-dimensional state-space, which could take 100 different states. 
So I set:

```
@property
    def states(self):
        return dict(act=dict(type='int', shape=(1,)))
```

(Maybe this is already wrong?)

Then I want to setup and agent (according to the [`quickstart`](https://github.com/reinforceio/tensorforce/blob/master/examples/quickstart.py)-example) an agent with

```
network_spec = [
    dict(type='dense', size=32),
    dict(type='dense', size=32)
]
agent = PPOAgent(
    states=environment.states, # = dict(act=dict(type='int', shape=(1,)))
    actions=environment.actions, # = dict(type='int', num_actions=100)
    network=network_spec
)
```

and with this it results the error:
`ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("ppo/actions-and-internals/layered-network/apply/dense0/apply/linear/apply/W/read:0", shape=(1, 32), dtype=float32)''`

which is think boils down to this line:

https://github.com/reinforceio/tensorforce/blob/35d309a4aabbc288539d3ad8255a202157f15a62/tensorforce/core/networks/layer.py#L593

where the weights are always setted to be type of `float` but the incoming data is of type `int` and tensorflow demands that the incoming data `a=x` equals in type the multiplied type `b=self.weights`.
Now I believe the weights should be of type `float` always, but then I wouldn't know how to set discrete states of type `int`... Ot must the weights-type be set to the one of the states? Or is this a problem in tensorflow itsself?

OK, this is where I'm puzzled, maybe someone knows an answer?

**Comment by AlexKuhnle** [comment]
Hi,
Integer values can indeed not directly processed by a dense layer. The [embedding layer](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/layer.py#L405) is one way to convert an integer input into a continuous embedding (plus potential flattening to get a rank-2 tensor).
