### ISSUE TITLE
OpenAI/Universe environment deprecated

### ISSUE THREAD

**Issue by daggertye** [reinforceio/tensorforce#442]
Hey,

The OpenAI universe [repository](https://github.com/openai/universe) is archived and is deprecated for python 3. Instead, they suggest [Retro](https://github.com/openai/retro). Can we provide support for this library as well?

**Comment by AlexKuhnle** [comment]
In principle, sure. Are you free to look into and contribute the interface? Otherwise might take some time, just getting started with support again.
