### ISSUE TITLE
Distribution Mode save/restore

### ISSUE THREAD

**Issue by lynic** [reinforceio/tensorforce#444]
I'm running the distribution mode in one machine the same as example shows. Can I specify the same saver directory in agent's spec? Will it cause any conflict between agents?

**Comment by lynic** [comment]
I try to save the agent-0's model and try to load it at single mode, but I got following error when trying to restore from saved model:

```
NotFoundError (see above for traceback): Key ppo/observe-timestep/optimization/reward-estimation/mlp-baseline/predict/prediction/apply/b not found in checkpoint
	 [[Node: save/RestoreV2_75 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_75/tensor_names, save/RestoreV2_75/shape_and_slices)]]
```

**Comment by AlexKuhnle** [comment]
Sorry for the late reply, just getting started with support again. I'll try to look into that soon.

**Comment by AlexKuhnle** [comment]
So you train a model in async mode, but then want to load it in single mode? Can you also post the config?

**Comment by lynic** [comment]
I modify episode_finished(r) and add following:

```
    if r.episode % 10 == 0 and r.agent.device == "/job:worker/task:0":
        log.info("Saving model...")
        r.agent.save_model("./models/models")
```

But it seems that I can not load this model from single mode, and in distributed mode, after I load this model, it seems that the network parameters didn't changed.

```
    nva = agent.model.session.run(agent.model.network.get_variables())
    if os.path.exists(pp+"models/"):
        log.info("Loading models...")
        agent.restore_model(pp+"models/")
        nvb = agent.model.session.run(agent.model.network.get_variables())
        assert not all([np.array_equal(v1, v2) for v1, v2 in zip(nva, nvb)])
```

I got an assert error here.

**Comment by AlexKuhnle** [comment]
I mean the config/arguments used to initialize the agent, that would be helpful. I will then try to reproduce the problem...

**Comment by lynic** [comment]
Basically I use this command:

```
python examples/openai_gym_async2.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json -e 10000 -m 200 -W 3
```

**Comment by AlexKuhnle** [comment]
@lynic, finally got around looking into this. First, I wouldn't recommend using the manual `save/restore_model` API, but instead use the `saver_spec` argument (fyi: it saves the variables of the global model, not one of the workers). Second, I fixed a problem which caused an error when loading an async trained model in single mode, but this should work now. Let me know if there are still problems...
