### ISSUE TITLE
Nested spaces.Dicts have no shape

### ISSUE THREAD

**Issue by ryou90** [reinforceio/tensorforce#446]
If we using nested Dicts, the parent Dict have no shape Key. But in the sanity_check_specs.py, the state will be checked, if shape is int.

```python
if isinstance(state['shape'], int):
   state['shape'] = (state['shape'],)
```

**Comment by AlexKuhnle** [comment]
Nested state/action structures are not currently supported, and I modified the OpenAIGym environment to un-/flatten them automatically -- which is the general way how to handle nested structures (for now). Haven't tested the code thoroughly yet, though, so let me know if there is a problem.
