### ISSUE TITLE
Environment for driving robot swarms

### ISSUE THREAD

**Issue by deeplearningrobotics** [reinforceio/tensorforce#447]
I release a framework for reinforcement learning of driving robot swarms. It supports tensorforce as a training backend as well as multiagent PPO.

Video: https://www.youtube.com/watch?v=GDV5NgrER5U&t=20s
Github: https://github.com/TensorSwarm/TensorSwarm

It could also serve tensorforce users as an example on how to create custom networks.

**Comment by daggertye** [comment]
Hi, I've taken a look at the repository, but am unsure how to integrate this into the main tensorforce framework. Perhaps a conversation with the code maintainers on gitter would be more helpful for integration or perhaps creating a tensorforce to conglomerate Multi-Agent RL environments and algorithms.

**Comment by deeplearningrobotics** [comment]
There are two issues with integration in tensorforce:

1. I use ROS to communicate with the simulation, so I would need to change to some standalone python communication middleware to communicate with the C++ simulation or provide a direct python interface to the simulation.

2. The tensorforce environment only supports one agent learning in parallel while the standalone PPO supports multiple agents. This means that the tensorforce environment stops working well when trying to train more than 4 robots in parallel. Extending tensorforce with multi-agent PPO or IMPALA would be cool, but I don't have enough insight into the tensorforce code to do it, at its genericity makes it, at least for me, complicated to extend.

**Comment by daggertye** [comment]
Alright then. 

This really isn't an issue then, though.

**Comment by AlexKuhnle** [comment]
The issue is that you cannot instantiate multiple agents, as each uses its own graph, and multiple graphs cause problems? But I agree, not really an issue. If you want to look into an implementation for TensorForce, feel free to do so and happy to try and be helpful, otherwise the upcoming [YARL project](https://github.com/YARL-project) might support what you're looking for.
