### ISSUE TITLE
Inconsistent action/actions argument name (Runner / Environment.execute)

### ISSUE THREAD

**Issue by benediktmu** [reinforceio/tensorforce#449]
In a recent commit (fd30c0fd7faa64f5df9232bfa75907b09dc377e9), the parameter name "action**s**" was changed to "action" in most environments. In execution/runner.py (line 104) "action**s**" is still used, which means most environments don't work. If "action" is to be the new name, I think the following environments will have to be changed too, because they still use "action**s**":

- DummyEnv
- OpenAIUniverse
- MazeExplorer
- MinimalTest

@daggertye : Maybe you already have the changes locally but they were missing from the commit?

**Comment by daggertye** [comment]
Yeah, I forgot this. The fix is in #451.
