### ISSUE TITLE
What's the proper way to have multiple states in nested dicts?

### ISSUE THREAD

**Issue by 16Aghnar** [reinforceio/tensorforce#450]
Hi,
I'm working on a project in which I need to feed the ANN with 2 different states of the system. As I understood, then my environment.states should be a dict with inside 2 dicts describing the 2 states. However, doing that fails, i got a TensorForceError in networks/network.py, line 277. it says that len(x)=2 and should be 1, and I believe that x is environment.states. Maybe tensorforce thinks that I have a unique state, but I don't see why it would fail to see the 2 states...
So, what's the proper way to have multiple states in nested dicts?

**Comment by AlexKuhnle** [comment]
Can you post your states_spec dict?

**Comment by 16Aghnar** [comment]
See below
```
dict(probes_state=dict(type='float',
                                    shape=(self.length_buf, self.nb_probes, )),
       paddles_state=dict(type='float',
                                      shape=(self.length_buf, self.nb_paddles, ))
```

**Comment by AlexKuhnle** [comment]
Ah, of course, if you have multiple input states, the normal network_spec does not work, as it assumes a sequence of layers to process _one_ input array. A simple solution would be to combine `self.nb_probes + self.nb_paddles`, a more general one would be to implement your own `NeuralNetwork` class or use the "complex network" specification.

**Comment by 16Aghnar** [comment]
Thanks for the answer. But then there are some things that are unclear for me, in the tensorforce code. these lines made me think that it was possible to have multiple input states. Could you explain me ?
In environments/environment.py, line 84 in ``` def states(self) ``` : 
``` Return the state space. Might include subdicts if multiple states are available simultaneously.  ```
In contrib/sanity_check_specs.py, lines 37 to 46
``` # Unique state shortform.
    is_unique = ('shape' in states)
    if is_unique:
        states = dict(state=states)

    # Normalize states.
    for name, state in states.items():
        # Convert int to unary tuple.
        if isinstance(state['shape'], int):
            state['shape'] = (state['shape'],) 
```
For me this handles cases with multiple input states
And finally, in models/model.py, lines 400 to 406 in ``` def setup_placeholders(self)  ``` : 
``` # States
        for name, state in self.states_spec.items():
            self.states_input[name] = tf.placeholder(
                dtype=util.tf_dtype(state['type']),
                shape=(None,) + tuple(state['shape']),
                name=('state-' + name)
             ) 
```
and isn't this creating one special placeholder for each input state?

**Comment by 16Aghnar** [comment]
oh, yeah, I get it ! thanks
