### ISSUE TITLE
DQN agent is broken?

### ISSUE THREAD

**Issue by madpower2000** [reinforceio/tensorforce#470]
I was trying to run demo with DQN agent from example folder like this:

`python3 examples/openai_gym.py CartPole-v0 -a examples/configs/dqn.json -n examples/configs/mlp2_network.json -e 2000 -m 200`

and got bunch of errors! With other type of agents (like vpg) example code runs fine.

**Comment by AlexKuhnle** [comment]
The latest commit should fix the problem. I know that error messages in TensorForce always look massive (due to internal architecture), but it was really just a very small type mismatch. :-)
