### ISSUE TITLE
Quick start example raises TypeError

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [reinforceio/tensorforce#48]
Fresh install. Command from http://tensorforce.readthedocs.io/en/latest/#quick-start:
```
python examples/openai_gym.py CartPole-v0 -a TRPOAgent -c examples/configs/trpo_agent.json -n examples/configs/trpo_network.json
```
Gives:
```
[2017-07-24 22:51:58,560] Making new env: CartPole-v0
Traceback (most recent call last):
  File "examples/openai_gym.py", line 121, in <module>
    main()
  File "examples/openai_gym.py", line 70, in main
    agent = agents[args.agent](config=agent_config)
  File "/home/tensorforce/tensorforce/agents/batch_agent.py", line 50, in __init__
    super(BatchAgent, self).__init__(config)
  File "/home/tensorforce/tensorforce/agents/agent.py", line 143, in __init__
    self.model = self.__class__.model(config)
  File "/home/tensorforce/tensorforce/models/trpo_model.py", line 54, in __init__
    super(TRPOModel, self).__init__(config)
  File "/home/tensorforce/tensorforce/models/policy_gradient_model.py", line 81, in __init__
    self.baseline = Baseline.from_config(config=config.baseline)
  File "/home/tensorforce/tensorforce/core/baselines/baseline.py", line 43, in from_config
    predefined=tensorforce.core.baselines.baselines
  File "/home/tensorforce/tensorforce/util.py", line 123, in get_object
    return obj(**full_kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)
```
`obj` from `util.py:119` is `<class 'tensorforce.core.baselines.mlp.MLPBaseline'>`, `kwargs` is `None` and `full_kwargs` is `{}`.

`MLPBaseline`'s `__init__` [indeed](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/baselines/mlp.py#L33) takes at least 2 arguments.

**Comment by michaelschaarschmidt** [comment]
Hi,
sorry, we changed some of the config keys and relied on the test to check if the example still runs: https://github.com/reinforceio/tensorforce/blob/master/tensorforce/tests/test_quickstart_example.py 

Will fix the config asap

**Comment by michaelschaarschmidt** [comment]
Ah, you are using the TRPOAgent config, not the trpo_cartpole.json config, hence we didnt catch it:

python examples/openai_gym.py CartPole-v0 -a TRPOAgent -c examples/configs/trpo_cartpole.json -n examples/configs/trpo_cartpole_network.json

This should run and I will check for outdated example configs such as trpo_agent.json now

**Comment by michaelschaarschmidt** [comment]
Fixed via https://github.com/reinforceio/tensorforce/commit/2017d3d8f0b4e63a0280a717fac625eeb2860cb8

**Comment by michaelschaarschmidt** [comment]
Docs now updated via https://github.com/reinforceio/tensorforce/commit/4ad49a2e77f1841e3ce55c9a3cb000d44b4a4acd

**Comment by AdamStelmaszczyk** [comment]
Thanks, no TypeError now.
