### ISSUE TITLE
Implementing reward shaping in TensorForce 

### ISSUE THREAD

**Issue by madpower2000** [reinforceio/tensorforce#483]
What if I will try to simulate game environment where every step produce some reward (positive or negative) and in the same time I have overall total score for whole game when episode is over. It may be some custom metric, which is different then just sum of every move rewards. How I can apply such scenario in tensor force framework?

**Comment by dwilson1988** [comment]
That can just be handled in the environment. The terminal state would return the reward from the end of the game, shaped within your environment class.

**Comment by AlexKuhnle** [comment]
Agree with @dwilson1988, best to incorporate it as part of your (custom) environment class. Note also that in the traditional RL setup there is one and only one reward signal per timestep, and most algorithms (all in TensorForce) thus require this one signal.

**Comment by madpower2000** [comment]
Thanks for your reply. But a more theoretical question: which order of magnitude should have a reward for each step in comparison with the final result? For example: the reward for each step is +1 or -1, depending on the result of the step (max_step=100); Win +1000, a losе of -1000 in the last step of the episode?

**Comment by AlexKuhnle** [comment]
Hard to say, sounds very much like a hyperparameter (balancing one with the other optimization goal) which you need to experiment with and tune to the problem.

**Comment by mecotiere** [comment]
@madpower2000  It's definitely an empirical solution
