### ISSUE TITLE
Infinite loop in unflatten_action

### ISSUE THREAD

**Issue by vermashresth** [reinforceio/tensorforce#486]
Hello
I noticed that when the action is a dictionary with keys of the form `action1`  or `action1-`, the control enters this code block [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/openai_gym.py#L213:L224) and it gets stuck in an infinite loop. I guess `n` has to be incremented there. Or am I missing something ?
Another thing I noticed is that  `isnumeric()` [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/contrib/openai_gym.py#L208) won't work on strings in python2 becuse they aren't unicode by default. Perhaps we should change it to `isdigit()` instead or explicitly convert the string into a unicode object?

**Comment by AlexKuhnle** [comment]
Both good points, will look into that soon.

**Comment by AlexKuhnle** [comment]
This should be solved now. Can you try again? I changed the prefix from `actionXXX` to `gymtplXXX` and others, so unlikely to cause a clash.
