### ISSUE TITLE
How to define multiple actions where some are available simultaneously ?

### ISSUE THREAD

**Issue by mecotiere** [reinforceio/tensorforce#489]
I'm trying to code a new environment and I'm currently unable to define a set of actions where there are an action comprising multiple actions + other simple actions.
That is, to simplify, I have two actions :

One with 3 float variables
`self._actions = dict(
       X=dict(type='float', min_value=-2.0, max_value=-0.05),
       Y=dict(type='float', min_value=0.05, max_value=2.0),
       Z=dict(type='float', min_value=-2.0, max_value=-0.05)
)`

And another simple one
`self._actions = dict(type='int', num_actions=1)`

How can I combine both ? I've tried to combine them in a list, a dict, a tuple but an error is raising.

Many thanks  !

**Comment by AlexKuhnle** [comment]
Think of TensorForce action spaces as flattened concatenations, so just add the latter specification to the former dictionary:
```
self._actions = dict( ..., A=dict(type='int', num_actions=1) )
```
However, `num_actions=1` in the latter doesn't make sense. Presumably what you mean is that there is only one discrete action value (which is implicitly the case by default `shape=()`). `num_actions` specifies the number of discrete alternatives of this action, so `num_actions=5` would give *one* action value from `{0, 1, 2, 3, 4}`.
