### ISSUE TITLE
Multi-threaded execution example

### ISSUE THREAD

**Issue by mecotiere** [reinforceio/tensorforce#495]
Would it be possible to get an example of how to launch a multi-threaded PPO ?

I guess we should change type to 'multi-threaded' given 'contrib/sanity_check_specs.py'

`execution=dict( 
        type='single',
        session_config=None,
        distributed_spec= None
    ),`

**Comment by mecotiere** [comment]
That was very helpful, thank you.

I've been able to implement it, nonetheless, it was slower than the single threaded version !

We should use a distributed engine like ray.

@AlexKuhnle What about [rlgraph](https://github.com/rlgraph/rlgraph) ? Is it based on tensorforce ?

**Comment by AlexKuhnle** [comment]
RLGraph is a new framework developed by some of the developers of TensorForce, insofar it's somewhat "based" on it (learnings etc), but it's an independent project. And yes, it's much more focused on distributed execution. I don't think the distributed execution part of TForce will be further developed, unless someone wants to properly join the project and look into it. At least I won't have time to do so anytime soon.

Closing the thread then.
