### ISSUE TITLE
Parallel reward computation for one agent with update_mode['batch_size'] > 1

### ISSUE THREAD

**Issue by Deathn0t** [reinforceio/tensorforce#498]
Hi,

I am working on a cluster. The function which compute the reward take some time in my case. Moreover to compute one reward I need a full episode, I don't have one reward corresponding with each action of an episode. So I would like to run this function in parallel, get all the rewards once they are computed then get the agent to learn.

After taking a look at different classes in tensorforce : Agent, PPOAgent Model, Environment and Runner.

I think that I need to create a new basic agent corresponding to Agent but for Parallel, mostly to modify the act, observe functions because I will have to compute batch_size episodes then get the rewards for all of them then observe, so the behavior of the `terminate` and the way they buffer are managed are going to be different.

About the Environment, I am accumulating the actions of the current_episode in a buffer so that I can launch my task here (because the environment should be responsible of computing the reward if I am right) but the reward will not be returned directly so rather than returning the reward I will return an object corresponding to my task (this is why I will need an adapted Runner).

Finally I will have to create a new Runner, where I am going to put my sync barrier.

Here is my understanding of Tensorforce, would you have some advice about these ideas ?

Thanks a lot for you help.

**Comment by AlexKuhnle** [comment]
Hi @Deathn0t, what you describe sounds about right. Rewards are calculated as part of the environment, and if you only have one final episode reward, it's best to give zero reward for every non-terminal timestep. You may have come across a batched `agent.act(...)` version, and in fact I would suggest extending this functionality to a proper parallel feature for the existing `Agent` class. I'm not sure about this part: "so rather than returning the reward I will return an object corresponding to my task" -- what do you mean here?

Happy to help you working on this if you plan to contribute. In that case, let's switch to Gitter for conversation...

**Comment by Deathn0t** [comment]
@AlexKuhnle I just finished something, and I did a test where the function which compute the final reward do `time.sleep(1)` before returning. In the actual tensorforce implementation the total time is 1034 sec and with my update it's taking 121 sec when the final best reward achieve is the same and the whole behavior of the reward history is the same too.

**Comment by AlexKuhnle** [comment]
Is this also solved via #508?

**Comment by Deathn0t** [comment]
yes, solved !

**Comment by Deathn0t** [comment]
Not really, to solve this issue I created a specific environment that return an asynchronous object as a reward, also I created a new runner, so that I can run in parallel the computation of many rewards and then use observe

**Comment by AlexKuhnle** [comment]
Hmm, do you consider it solved, though (if so, feel free to close the issue)? And/or is it a very specific solution or generally useful and contribution-worthy?

**Comment by Deathn0t** [comment]
My actual solution is problem specific. If I think about something more general I'll add the feature in tensorforce. For now I am closing the issue. If anyone needs informations about the solution feel free to contact ask.
