### ISSUE TITLE
AttributeError: 'Linear' object has no attribute 'trainable'

### ISSUE THREAD

**Issue by Jonathan-Livingston-Seagull** [reinforceio/tensorforce#504]
I get this exception when I try to run DQN agent. I made an inspection and found out that "trainable" property is not set in the Linear Layer. I have updated the code and created a pull [request.](https://github.com/reinforceio/tensorforce/pull/503)

**Comment by AlexKuhnle** [comment]
Great, thanks for providing the solution right away. :-)
