### ISSUE TITLE
Stateful for LSTM

### ISSUE THREAD

**Issue by Deathn0t** [reinforceio/tensorforce#517]
Hi,

It can be good to add a `stateful` parameter in a runner in order to activate/deactivate the `agent.reset()` when starting a new episode. For the LSTM, it's very important to pass the last internal state of the previous episode to the new episode. Here are some explanations : http://philipperemy.github.io/keras-stateful-lstm/

the modification will just be to add a boolean `stateful` as an argument of the `__init__` of a Runner. And add a `if` condition on the `agent.reset()`

**Comment by AlexKuhnle** [comment]
Hi @Deathn0t, I don't think that applies here. Within an episode, an LSTM should be stateful over timesteps (that is what the `InternalLSTM` layer is supposed to do), but a new episode is a new beginning and an agent's internal state should not influence this "new beginning". Does that make sense?

Unfortunately, `InternalLSTM` and generally internal states are not trained properly, a long-standing issue that I never got around to solve so far (not because it's unclear how, just because it's a very involved modification). I'm keen to finally get this sorted out at some point, though.

**Comment by Deathn0t** [comment]
Hi @AlexKuhnle there are cases where the `state` of the first timestep of an episode is just a fixed constant value without any meaning and the actual meaningful state is the input hidden state of the LSTM. I ran some test and it appears that if you don't use a stateful LSTM the first action will not learn well.

**Comment by AlexKuhnle** [comment]
I see -- in that case I would suggest using a trainable variable as initial state, would that work? My impression is still that it would be weird if the end of an episode influences the internal state of a next episode.

**Comment by Deathn0t** [comment]
I am using 'lstm' not 'internal_lstm'.

**Comment by AlexKuhnle** [comment]
Hmm, maybe I have a wrong situation in mind. What is the `states` specification, and in what sense does the last internal state of an episode influence the beginning of a new episode? Because LSTM doesn't at all transfer hidden states between timesteps, afaik...

**Comment by Deathn0t** [comment]
It's about the interpretation of LSTM, not much theory here. One part of the LSTM hidden state is the memory. So that you are acting at the current timestep given your previous actions. If you are playing different episodes, let's say an episode is like playing a game from the beginning to the end. You can transfer the hidden state to the next episode so that you are playing a new game remembering your past actions.

**Comment by AlexKuhnle** [comment]
Okay, then I think the way you suggested to implement it should be okay. However, I wouldn't add this as a proper TensorForce feature, though (for now), as an episode in general RL is a complete and "isolated" unit with no information flow beyond (in my understanding).

Closing this, but feel free to post here if there are problems/updates.
