### ISSUE TITLE
Incorrect number of columns computing lower triangular matrix in NAF agent

### ISSUE THREAD

**Issue by fvncc** [reinforceio/tensorforce#52]
In naf_model.py, lines 71-79:

```
     if num_actions > 1:
                offset = num_actions
                l_columns = list()
                for zeros, size in enumerate(xrange(num_actions - 1, 0, -1), 1):
                    column = tf.pad(l_entries[:, offset: offset + size], ((0, 0), (zeros, 0)))
                    l_columns.append(column)
                    offset += size
                l_matrix += tf.stack(l_columns, 1)
```

I believe the number of columns given to tf.stack is incorrect (one too few). I think there needs to be an extra column, e.g. by adding something like:

`l_columns.append(tf.zeros_like(l_columns[0]))`

Is this correct?

The error I'm getting is:

ValueError: Dimensions must be equal, but are 59 and 58 for 'training_outputs/add' (op: 'Add') with input shapes: [?,59,59], [?,58,59].

from the line

`l_matrix += tf.stack(l_columns, 1)`

**Comment by AlexKuhnle** [comment]
This was due to a bug, which should be fixed now. I will close this issue, but feel free to open it again if it didn't help.

**Comment by fvncc** [comment]
Thanks seems to be working now :)
