### ISSUE TITLE
Feed a value for placeholder tensor 'ppo/initialize/episode_index'

### ISSUE THREAD

**Issue by tdjogi010** [reinforceio/tensorforce#521]
Hey,

I am getting an error 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'ppo/initialize/episode_index' with dtype int32
	 [[{{node ppo/initialize/episode_index}} = Placeholder[dtype=DT_INT32, shape=[], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```
with stack trace [log.txt](https://github.com/reinforceio/tensorforce/files/2454175/log.txt) or [gist](https://gist.github.com/tdjogi010/64b3c33d0ac9a9cc68bf7e4dbf3f3874) while restoring the model (see the steps to reproduce below). 

Steps to reproduce:
1. Edit the directory value with a string (say "./tmp/" instead of null) in saver spec of ppo.json. Also edit seconds to smaller value just for the sake of shorter interval
2. Run `python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json
`
3. Stop the program after few minutes
4. Run the command in (2) again. You will see the error. 

Please do let me know if it is not the way to save and restore a model. I resolved it by feeding value to placeholder i.e 
```session.run(fetches=self.buffer_index_reset_op, feed_dict={self.episode_index:0})```
 on line 700 in `model.py`. But, I think there should be a better way.

**Comment by AlexKuhnle** [comment]
I modified `model.py` to hopefully solve this problem (fyu @Deathn0t). Let me know if that doesn't work.
