### ISSUE TITLE
Option: --load Episode_index problem

### ISSUE THREAD

**Issue by mbertrait** [reinforceio/tensorforce#522]
Hi,

I'm currently experiencing a problem with Tensorforce. This error comes up when trying to load a previously saved model (PPO but I think it doesn't matter). I already have this issue by the past and it has been caused by the initialization of the episode_index attribute of the Model class (model.py). It was working at the commit [cee7478](https://github.com/reinforceio/tensorforce/commit/cee78736079c05a9dc1a91e57373aa93c9d3f3c1) but the latest commits get everything kaput (as I presume).

Here is the stated error: 
```console
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'ppo/initialize/episode_index' with dtype int32
```

Sincerely.

**Comment by Deathn0t** [comment]
Hi @mbertrait, Are you trying to restore a model saved before we made the modification with observe(...,index) and act(...,index), corresponding to this PR : #508 ?

**Comment by AlexKuhnle** [comment]
That sounds like it could be the case, and if so, up to [this commit](https://github.com/reinforceio/tensorforce/commit/d1a9ecf9d02c5b0d36864e3979426b1caef62b11) it should work. Well, if so, maybe we should have integrated the feature with backwards-compatibility in mind. :-)  But if you take one of the older versions for this trained model, and for new models from now on the latest commit, that should hopefully help. Does that work?
