### ISSUE TITLE
Network with Loops

### ISSUE THREAD

**Issue by hfurkanbozkurt** [reinforceio/tensorforce#527]
Hello, I am trying to implement a network where I can have loops. For example, a typical workflow is as follows:
```
Agent and Model sees a network which takes three inputs where
    original state:      a, b, c

However, we want to have a network which takes two inputs and 
computes the output for the original state using subsets of it.

first pass:
    input_1:             a, b
    (based on the first pass output, we form the second input)
    (lets say we have a softmax which determines including a or b in the next pass along with c)

second pass:
    input_2:             b, c
    (second pass output is the actual output)
```
I believe I should implement this in the network level. Right now, I am trying to implement this structure in tf_apply in my custom layer however I could not succeed. Can you give me some pointers for where to start and what to use?

**Comment by AlexKuhnle** [comment]
It sounds like the network is the right place, yes. Well, if you always have this setup, there is no need to actually use TensorFlow loops (which may cause all sorts of problems, as they do/did in other places within TensorForce). What you can do is the following:

1. You write a custom class inheriting from `LayerBasedNetwork` or `Network`.
2. You define all the _actual_ layers you need, that is, excluding second 'calls' to the same layer sharing variables.
3. Similar to [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/network.py#L243) you then define what the network looks like, calling layers like [this](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/network.py#L259).

A very simple network could, for instance, look something like this (semi-pseudocode, `[...]` concatenation, for instance):

```
def tf_apply(a, b, c, update, ...):
    ab = self.layer.apply(x=[a; b], update=update)
    output = self.layer.apply(x=[ab; c], update=update)
    return output
```

This would apply the same layer first to `a` and `b`, then to their output `ab` and `c`. Is that what you want? If so, let me know if it works... :-)

**Comment by hfurkanbozkurt** [comment]
Hello @AlexKuhnle, thank you for your help. It works like a charm :)
