### ISSUE TITLE
agent parameters schedule

### ISSUE THREAD

**Issue by jerabaul29** [reinforceio/tensorforce#528]
I was reading a bit about metaparameter tuning of PPO here:

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-PPO.md

One of the parameters that seem important to tune is the Beta parameter (strength of entropy regulatization, so if I am right the *entropy_regulatization* entry in the PPOAgent setup). They say that one should monitor the decay of the entropy to check the value of this parameter.

How could I monitor this entropy decay?

Do you think it would be a good idea to be able to set up a 'schedule' for this value?

**Comment by AlexKuhnle** [comment]
Should be possible with the `'entropy'` label for TensorBoard summaries, committed a small fix which caused it to not be reported unless `entropy_regularization` was turned on...
