### ISSUE TITLE
Documentation for epsilon decay

### ISSUE THREAD

**Issue by mryellow** [reinforceio/tensorforce#53]
It's not the linear decay based on the remaining I was expecting.

`self.epsilon -= ((self.epsilon - self.epsilon_final) / self.epsilon_timesteps) * timestep`

So over 100 steps that takes about 30-40 to get "close" to `epsilon_final`.

Potential for optional decay mode.

**Comment by mryellow** [comment]
This is an implementation of what I was expecting:

https://github.com/karpathy/convnetjs/blob/9a3fc7be4d47871497a95dd357e52c9190b2c06d/build/deepqlearn.js#L183

In python:

`self.epsilon = min(1.0, max(self.epsilon_final, 1.0-(timestep - self.first_update)/(self.epsilon_timesteps - self.first_update))); `

Though `first_update` isn't defined under `exploration` key of config.

**Comment by krfricke** [comment]
Thanks @mryellow for closing this with #56
