### ISSUE TITLE
examples/openai_gym can not work with dqn

### ISSUE THREAD

**Issue by g8787856** [reinforceio/tensorforce#531]
Hi,

I am learning reinforcement learning and trying to run some code,
so I was trying to run example with DQN agent and CNN network, this is my command:

python examples/openai_gym.py CartPole-v0 -a examples/configs/dqn.json -n examples/configs/cnn_dqn_network.json

it's got error with:
Invalid input rank for conv2d layer: 2, must be 4

Can somebody tell me why?

**Comment by AlexKuhnle** [comment]
Hi @g8787856, a CNN network only makes sense if you have image-like states, like the current screen in the case of Atari games. CartPole does have a much smaller and differently shaped input, so you should use something like the `mlp2_network.json` network.
