### ISSUE TITLE
Use myself agent and environment

### ISSUE THREAD

**Issue by marooncn** [reinforceio/tensorforce#536]
Hi, I want to use a robot named mir100 in  maze in gazebo, which is a robot simulator, I am not sure if it's convenient to use tensorforce to apply various RL algorithms to realize the navigation task and compare their behaviors. Any advice? Thank you.

**Comment by AlexKuhnle** [comment]
I would definitely say that this is the case, at least that's one of the main motivations for Tensorforce. Deep RL is obviously a rather early research topic, so things may not always be working smoothly, but again, Tensorforce aims to help practitioners avoid many of the common issues. Feel free to get in touch via Gitter if you want to discuss things more.
