### ISSUE TITLE
Exploration could be max until learning starts

### ISSUE THREAD

**Issue by mryellow** [reinforceio/tensorforce#57]
Perhaps `first_update` could be copied into `config['exploration']`.

Would be used like this:

https://github.com/reinforceio/tensorforce/pull/56/files#diff-3a20a353542fac38371e6c75dccfe10fR31

Similarly for `EpsilonDecay`:

`self.epsilon -= ((self.epsilon - self.epsilon_final) / (self.epsilon_timesteps - self.first_update)) * (timestep - self.first_update)`

edit: With a `min` and/or `max` to ensure `timestep - first_update` doesn't throw things off.

**Comment by krfricke** [comment]
We added the `start_after` parameter to epsilon_decay and epsilon_anneal in ab87bbb20f5ba4bb474afefbd05531a23665e1d6. The parameter can be specified in the exploration configuration. We don't copy the `first_update` parameter, as the two values should be configurable indivdually.
