### ISSUE TITLE
Options of strategy about experience sampling at Replay.get_batch.

### ISSUE THREAD

**Issue by nagachika** [reinforceio/tensorforce#60]
Current Replay.get_batch return the samples as continuous range of original sequence of experiences.
I'd like to get batch data whose each sample is picked up from memory at random to get rid of bias of samples.
I would like to add an option to change the strategy about sample in Replay.get_batch.

See https://github.com/reinforceio/tensorforce/pull/59

**Comment by michaelschaarschmidt** [comment]
Fixed in https://github.com/reinforceio/tensorforce/commit/31df6eddfc582642da3e1b8be354ed8c1e8c555b
