### ISSUE TITLE
Handle next state semantics in case of random sampling

### ISSUE THREAD

**Issue by michaelschaarschmidt** [reinforceio/tensorforce#69]
DQN/DQFD/NAF assume continuous sequences of states, thus do not need to explicitly handle next states, but as we introduced random sampling, this needs to be taken care of. Turned random sampling off by default

**Comment by Islandman93** [comment]
Sequential sampling must make sure that no terminals exist in any index but the last. Otherwise the agent is receiving a state from one episode and a state (t+1) from the next episode. Similarly, when random sampling the terminal state must always be in the state (t+1) position.

**Comment by AlexKuhnle** [comment]
Added `next_state` placeholder in `QModel`, a new base class for DQN, DQFD and NAF. Also added functionality to retrieve `next_states` values from memory via `next_states=True` boolean flag in `Memory.get_batch`. Memories still assume that observations are observed in temporal order.

**Comment by AlexKuhnle** [comment]
Regarding your comment, @Islandman93, the case of terminals should be handled by the line `q_target = reward + (1.0 - terminal) * config.discount * self.target_values[name]`, unless I'm mistaken?

**Comment by Islandman93** [comment]
No you're correct
