### ISSUE TITLE
Alternating act and observe

### ISSUE THREAD

**Issue by Tjorriemorrie** [reinforceio/tensorforce#71]
Hi, just curious about your statement in your blog:
> on-policy batches (BatchAgent). Note that for the agent’s internal mechanisms to work correctly, these functions have to be called alternately. 

What do you suggest I do when I have about 5 actions to take and no clue what the reward will be till the episode is over? Is it mandatory for the alternation and should I call observe with 0 till the last action when the reward will become known? Will the policy then update the previous actions?

**Comment by michaelschaarschmidt** [comment]
This only matters if you have internal recurrent state, so you can call act without observe. Nonetheless, observing 0 reward would be a more typical RL setting.
