### ISSUE TITLE
A Distributional Perspective on Reinforcement Learning：code

### ISSUE THREAD

**Issue by zdx3578** [reinforceio/tensorforce#74]
A Distributional Perspective on Reinforcement Learning：code：
https://github.com/go2sea/C51DQN
https://github.com/Kiwoo/distributional_perspective_on_RL

**Comment by michaelschaarschmidt** [comment]
Closed via PR https://github.com/reinforceio/tensorforce/commit/bf8fcd638f1d834c6aa575b1dc1dd488ff756c13
