### ISSUE TITLE
tensorboard not showing values

### ISSUE THREAD

**Issue by Tjorriemorrie** [reinforceio/tensorforce#77]
Hi, is there anything specific to set up tensorboard?

I've added it to the config:
> tf_summary=path.join(self.MODEL_PATH, 'summary'),

and the files gets written to the folder. Also in tensorboard I can see the graph, but there are no values for metrics and histograms. I see the doc states it must be a boolean value - so I'm not sure if my model is wrong or if it is not writing correctly. Is there any example for me to compare?

**Comment by michaelschaarschmidt** [comment]
Hi,

we have not integrated this yet, it's on the to do list, thus far we have mostly been using loggers to log stuff. The summary writer only logs things you explicitly tell it to, so we have only been writing the graph so far.

**Comment by michaelschaarschmidt** [comment]
Merged #86
