### ISSUE TITLE
ValueError: Cannot feed value of shape (1,) for Tensor u'placeholder/state:0'

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [reinforceio/tensorforce#84]
I'm given [`RunEnv`](https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L14) that implements OpenAI's [`Env`](https://github.com/openai/gym/blob/master/gym/core.py), one can think of it as `class RunEnv(Env)`.

I would like to try TensorForce algorithms with `RunEnv`.

TensorForce implements its own [`Environment`](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/environments/environment.py), that does not derive from OpenAI's `Env`, but they look similiar. 

So I wrote such experimental [wrapper](https://gist.github.com/AdamStelmaszczyk/783c93be639d2e23ebddd8db4c9d52f7#file-tensor_force_env-py).

However, when I'm running [slightly modified `quickstart.py`](https://gist.github.com/AdamStelmaszczyk/783c93be639d2e23ebddd8db4c9d52f7#file-quickstart-py):

```
Updating Model file from 30000 to latest format...
Loaded model gait9dof18musc_Thelen_BigSpheres.osim from file /usr/local/lib/python2.7/dist-packages/osim/env/../models/gait9dof18musc.osim
env.states: {'shape': (41,), 'type': 'float'}
env.actions: {'max_value': 1.0, 'shape': (18,), 'min_value': 0.0, 'continuous': True}
[2017-08-05 22:30:29,334] Configuration values not accessed: loglevel
Traceback (most recent call last):
  File "quickstart.py", line 68, in <module>
    runner.run(episodes=1000, max_timesteps=200, episode_finished=episode_finished)
  File "/home/adam/Desktop/running/tensorforce/tensorforce/execution/runner.py", line 136, in run
    action = self.agent.act(state=state)
  File "/home/adam/Desktop/running/tensorforce/tensorforce/agents/agent.py", line 215, in act
    self.current_action, self.next_internal = self.model.get_action(state=self.current_state, internal=self.current_internal, deterministic=deterministic)
  File "/home/adam/Desktop/running/tensorforce/tensorforce/models/model.py", line 221, in get_action
    fetched = self.session.run(fetches=fetches, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1,) for Tensor u'placeholder/state:0', which has shape '(?, 41)'
```

41 is the length of the observation vector. As you can see, `env.states` holds the correct `shape`.

Help appreciated.

**Comment by michaelschaarschmidt** [comment]
Hello,

this is not a bug in tensorforce but a problem using TensorFlow, so not an issue for this repo

Second, maybe have a look at https://github.com/reinforceio/tensorforce/tree/master/tensorforce/contrib to see how other people implemented custom environments.

Your parser is creating the wrong shape apparently. The agent expects the shape you provided. Clearly, there is a mismatch between the shape provided by your parser and the shape provided by the environment when you act.

Basic tensorflow debugging would be to print out the tensors and see where dimensions are misaligned. Print the state you are feeding in. You will find the issue by comparing the shapes of things.

**Comment by XueminLiu111** [comment]
I have the same problem. Can anyone help?

**Comment by AlexKuhnle** [comment]
Since this issue is super-old, can you open a new issue with exception trace etc? So many changes in the meantime that it can't really be exactly the same issue.
