### ISSUE TITLE
QModel errors with LSTM

### ISSUE THREAD

**Issue by mryellow** [reinforceio/tensorforce#89]
With MountainCar:

 `W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,2] has negative dimensions`

End of the trace (but different environment, MazeExplorer):
`InvalidArgumentError (see above for traceback): Shape [-1,9,3] has negative dimensions`

Works previous to this commit:
https://github.com/reinforceio/tensorforce/commit/b0fd7d13ff1392c60dfef432bfea7a7dd035f71f

Test duplicating error:
https://github.com/reinforceio/tensorforce/pull/88

> mryellow @mryellow 09:38
> Possibly something to do with `QModel.update_feed_dict()` and `get_batch()` changes.

> Islandman93 @Islandman93 09:46
> I think it's probably the target network isn't getting lstm state

**Comment by AlexKuhnle** [comment]
Problem solved now.
