### ISSUE TITLE
Quickstart example doesn't work

### ISSUE THREAD

**Issue by nikoliazekter** [reinforceio/tensorforce#91]
Learning finished. Total episodes: 3000. Average reward of last 100 episodes: 17.76.

That doesn't look right.

**Comment by michaelschaarschmidt** [comment]
We are trackin this here:
https://github.com/reinforceio/tensorforce/issues/64

TRPO has a numerical issue that makes it crash occasionally, PPO and VPG work well. I will change quickstart to PPO for now

**Comment by michaelschaarschmidt** [comment]
Changed quickstart to PPO
